### ISSUE TITLE
junit output does not work when configured in behat.yml file

### ISSUE THREAD

**Issue by bla-kw** [Behat/Behat#1009]
When I put the format configuration in the command line it does work as expected:
```$ behat --format=junit --out=results/xml --format=pretty --out=std```

But when I put it in behat.yml file like this it does not work
```
testoutput:
  formatters:
    junit: [results/xml/]   <--- does not work
    pretty: [std]           <-- does work
```
When I have _junit: [results/xml/]_ in the config file I get this error message:
```
$ behat --profile=testoutput
[Symfony\Component\Console\Exception\InvalidArgumentException]
  The StreamOutput class needs a stream as its first argument.
```
I use behat version 3.3.0

**Comment by kgogolek** [comment]
+1 having the same issue. more documentation around formatters would be much appreciated.

**Comment by everzet** [comment]
Try:

```
testoutput:
  formatters:
    junit:
      output_path: "results/xml/"
```

Formatters are configured through child options.
