### ISSUE TITLE
Error when running test with Behat 3 in Jenkins

### ISSUE THREAD

**Issue by Nguonchhay** [Behat/Behat#1013]
I faced this problem when running behat at Jenkins with profile latest (-p latest)

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
17:08:39   Unrecognized option "Behat\MinkExtension" under "testwork" 

```
default:
  autoload:
    '': %paths.base%/tests/features/bootstrap
  extensions:
    Laracasts\Behat:
      #env_path: .env.behat
    Behat\MinkExtension:
      show_cmd: 'open %s'
      base_url: http://test.local.customer-portal.wehost.asia:8080
      browser_name: chrome
      default_session: selenium2
      laravel: ~
      selenium2:
        wd_host: http://10.10.10.120:4444/wd/hub

    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: uat-report
      print_args: true
      print_outp: true
      loop_break: true
  formatters:
    pretty: true
    junit:
      output_path: ./build/logs
    html:
      output_path: ./build/logs

  suites:
    default:
      paths: &featurePaths
        - '%paths.base%/tests/features/default'
      contexts: &contexts
        - FeatureContext
        - XmlContext
        - ResponsiveContext
        - ApplicationContext
        - MailHogContext:
            mailhogUrl: 'http://mail:8025'

      filters:
        tags: ~@skip

    smoke:
      paths:
        - '%paths.base%/tests/features/smoke'
      contexts:
        - FeatureContext
        - XmlContext
        - ResponsiveContext
      filters:
        tags: ~@skip

# For running test on local in chrome with selenium
local:
  extensions:
    Laracasts\Behat:
      env_path: .env.behat
    Behat\MinkExtension:
      selenium2:
        wd_host: http://dockerhost:4444/wd/hub

# For running test on local in chrome with selenium
latest:
  extensions:
    Laracasts\Behat:
      env_path: .env.behat
  Behat\MinkExtension:
    base_url: http://www.test.latest.customer-portal.wehost.asia

# For running test on local in chrome with selenium
demo:
  Behat\MinkExtension:
    base_url: http://www.demo.customer-portal.wehost.asia
```

Could some know how to fix it?
