### ISSUE TITLE
Define custom sessions in the behat.yml

### ISSUE THREAD

**Issue by SamyOteroGlez** [Behat/Behat#1031]
Hi all.
It's there a way to define custom sessions in the behat.tml?

I'm thinking in something like

```
Behat\MinkExtension:
            goutte: ~
            sahi: ~
            myCustomDriver: ~
            selenium2: ~
                #wd_host: "http://127.0.0.1:4444/wd/hub"
            default_session: goutte
            sahi_session: sahi
            myCustomDriver_session: myCustomDriver
            javascript_session: selenium2
            base_url: "http://localhost:8000/"
```

Thanks

**Comment by stof** [comment]
This issue has nothing to do with Behat itself, but with MinkExtension. So it should have been opened on https://github.com/Behat/MinkExtension. But I will answer anyway.

there is 2 different things here which could match your question:

- having multiple sessions but using available drivers (so having multiple sessions using the selenium2 driver for instance). This is supported in MinkExtension 2+ (so when using Behat 3) by using the full configuration format instead of the shortcut one:
  ```yaml
  default:
    extensions:
      Behat\MinkExtension:
        default_session: first_session
        sessions:
          first_session:
            selenium2: ~
          second_session:
            selenium2: ~
  ```
- registering custom drivers. This requires writing a Behat extension providing the necessary integration. This is how the Symfony2Extension can register a `symfony2` driver for MinkExtension (note that once the driver is registered, it can be used both using the shortcut or the full format).
