### ISSUE TITLE
Behat 3 - Issue communicating between contexts - registration error?

### ISSUE THREAD

**Issue by davebirch** [Behat/Behat#1042]
I'm following the instructions in:
http://docs.behat.org/en/latest/cookbooks/accessing_contexts_from_each_other.html

I have a number of contexts registered in behat.yml:
```
    suites:
        testSuite:
            paths:
              - %paths.base%/features
            contexts:
              - \BehatTests\AbstractContext
              - \BehatTests\AbstractReviewContext
              - \BehatTests\ActivityContext
              - \BehatTests\ApiContext
              - \BehatTests\BrowseContext
              - \BehatTests\BrowserSessionContext
              - \BehatTests\ChangeContext
              - \BehatTests\CommentContext
              - \BehatTests\CommonContext
              - \BehatTests\DashboardContext
              - \BehatTests\EmailContext
              - \BehatTests\FeatureContext
              - \BehatTests\FeatureMinkContext
              - \BehatTests\FileContext
              - \BehatTests\GroupContext
              - \BehatTests\JobContext
              - \BehatTests\LoginContext
              - \BehatTests\NotificationContext
              - \BehatTests\P4Context
              - \BehatTests\ProjectContext
              - \BehatTests\ReviewContext
              - \BehatTests\UserContext
```

All of my contexts except the FeaureMinkContext, extend AbstractContext in order to share a number of common methods from there, however, due to needing the extend MinkContext, I can't do this with my FeatureMinkContext...

As such, I implemented the suggestion in the linked manual page, however, whenever behat calls my BeforeScenario method that should set my AbstractContext instance from within FeatureMinkContext (or any other context from within any other context), I see the following error:

`
'AbstractContext' context is not found in the suite environment. Have you registered it?
`

I've tried passing the context name including the namespace as they're loaded in behat.yml but with no luck.

Any suggestions on what I'm doing wrong?
