### ISSUE TITLE
Cannot find step definitions when using *.scenarios list file

### ISSUE THREAD

**Issue by watermanio** [Behat/Behat#1060]
I'm trying to use a `.scenarios` file to balance tests in CI. 

My `behat.yml` config file has several testsuites and looks a bit like this:

```yaml
default:
  suites:
    core:
      paths:
        - "%paths.base%/features/Core"
      contexts:
        - Acme\CoreBundle\Behat\DatabaseSetupContext

    login:
      paths:
        - "%paths.base%/features/Login"
      contexts:
        - Acme\CoreBundle\Behat\DatabaseSetupContext
        - Acme\LoginBundle\Behat\LoginContext
```

When I run `vendor/bin/behat features/Login/login.feature` I get passing tests ✅ .

However, if my build script creates the following file `behat.scenarios`:

```
features/Login/login.feature
```

And then I run `vendor/bin/behat behat.scenarios`, most tests are skipped showing `U` - undefined step definition. 

Is this expected behaviour when using multiple testsuites? Or alternatively, is there another way to specify multiple feature files in one command line argument??
