### ISSUE TITLE
3.4 breaks accessing symfony2 parameters in behat.yml 

### ISSUE THREAD

**Issue by yakobe** [Behat/Behat#1077]
After updating to 3.4 it is no longer possible to access symfony2 parameters from the behat.yml as stated in the [docs](http://behat.org/en/latest/cookbooks/integrating_symfony2_with_behat.html#accessing-symfony2-parameters-in-behat-yml)

```
default:
    suites:
        default:
            contexts:
                - FeatureContext:
                    mySymfonyParam: %%my.symfony_param%%
    extensions:
        Behat\Symfony2Extension: ~
```

This now produces an error:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "my.symfony_param".
```
