### ISSUE TITLE
Exclude filter by name or role

### ISSUE THREAD

**Issue by hackel** [Behat/Behat#1091]
It seems that the exclude syntax (~) only works for tags.  It would be useful if I could use it for roles or feature names also, as in:
```yml
default:
  suites:
    user:
      filters:
        tags: ~@browser
        role: ~admin
    admin:
      filters:
        role: admin
```
Is there a way to achieve this currently?
