### ISSUE TITLE
Behat with Firefox-node error, Could not open connection: Payload received from webdriver is valid but unexpected json: ..

### ISSUE THREAD

**Issue by izbatt** [Behat/Behat#1121]
I'm having an issue connecting behat with the docker selenium firefox node through grid. I keep getting a "Could not open connection: Payload received from webdriver is valid but unexpected json: ..."
If I watch the test, Firefox starts and freezes. It never loads any pages i'm directing it to and fails out on the first step "Given I am on "/" see below for actual error.
I am able to connect and run all my tests just fine with the chrome node but I'm running into some issues with my tests and wanted to double check with another browser to determine if it's a chromedriver issue or not.

I have opened a ticket at [docker-selenium 665](https://github.com/SeleniumHQ/docker-selenium/issues/665) and they requested I open one here also. 
Any help or direction to get this solved would be greatly appreciated.

behat.yml
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      browser_name: 'firefox'
      javascript_session: selenium2
      goutte: 
        guzzle_parameters:
          verify: false
      selenium2: 
        wd_host: 'http://10.11.13.1:4444/wd/hub'
        capabilities:
          browserName: 'firefox'
          browserVersion: '*'
          marionette: true
      base_url: https://172.18.0.1 #localhost
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drush:
        root: '/var/www/vendor/drush/drush'
      drupal:
        drupal_root: '/var/www/web'
```

Meta -
Image(s):
selenium/hub
selenium/node-firefox-debug
Docker-Selenium Image Version(s):
latest
Docker Version:
17.12.0-ce
OS:
Ubuntu 16.04

-->

Expected Behavior -
For Firefox to open and run tests.

Actual Behavior -
```
@api @javascript
  Scenario: Test user login link while authenticated.                            # features/eva.feature:10
    Given I am on "/"                                                            # Drupal\DrupalExtension\Context\MinkContext::visit()
      Could not open connection: Payload received from webdriver is valid but unexpected json: {"value":{"sessionId":"34a26006-2510-4400-9e39-a8b74a655176","capabilities":{"moz:profile":"/tmp/rust_mozprofile.Xa1n21MpYjLo","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"pageLoadStrategy":"normal","moz:headless":false,"moz:accessibilityChecks":false,"acceptInsecureCerts":false,"browserVersion":"57.0.4","platformVersion":"4.13.0-31-generic","moz:processID":319,"browserName":"firefox","platformName":"linux","moz:webdriverClick":false}}} (Behat\Mink\Exception\DriverException)
    And I am logged in as a user with the "Authenticated user" role on this site # FeatureContext::assertAuthenticatedByRoleOnThisSite()
    And I wait for 1 seconds                                                     # FeatureContext::iWaitForSeconds()
    Then the href of ".header-user a" should be "/user"                          # FeatureContext::theHrefShouldBe()

--- Failed scenarios:

    features/eva.feature:10

1 scenario (1 failed)
4 steps (1 failed, 3 skipped)
```
