### ISSUE TITLE
Behat cannot find my specific context in given architecture

### ISSUE THREAD

**Issue by Drillan767** [Behat/Behat#1125]
Hello, I'm having trouble with the Behat architecture.
I need to create some tests for several projects at the same time. Let's say my Behat architecture is the following:

```
│   composer.json
│   composer.lock
│   default.behat.yml
│   
└───bin
│       behat
│       behat.bat
│       
└───features
   └───bootstrap
   │       FeatureContext.php ('default' feature context file)
   │
   └───project 1
   │   │   behat.yml (each behat.yml is copied from the the root folder one)
   │   │
   │   └───Big scenario 1
   │   │       test1.feature
   │   │       test2.feature
   │   │
   │   └───Big scenario 2
   │             test1.feature
   │
   └───project 2
       │   behat.yml (each behat.yml is copied from the the root folder one)
       │
       └───bootstrap
       │        Project2Context.php (extending 'features/bootstrap/FeatureContext.php')
       │
       └───Big scenario 1
                 test1.feature
                 test2.feature
                 test3.feature
```

The main goal behind all this is to be able to launch a command such as `bin/behat --config features/project2/behat.yml`. However, I'm getting trouble reaching the "Project2Context.php". Here is the content of the behat.yml in the "project 2" folder:

```
default:
  autoload:
    '': %paths.base%/features/project2/bootstrap
  suites:
    default:
      contexts:
        - bootstrap/Project2Context
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
  gherkin:
     cache: ~
  extensions:
    Behat\MinkExtension:
      base_url: http://www.website.rec
      sessions:
        default:
          goutte: ~
        javascript:
          selenium2:
            browser: phantomjs
    Drupal\DrupalExtension:
      blackbox: ~
```

I must admit I have huge trouble understanding how I can targer my context files, and finding examples online.

Thank you in advance
