### ISSUE TITLE
How to place the FeatureContext in custom directory

### ISSUE THREAD

**Issue by bartonhammond** [Behat/Behat#1128]
Here's the relevant part of my `wordhat.yml`:
```
default:
  suites:
    wordhat_features:
      paths:
         - "%paths.base%/features/wordhat"
      contexts:
        # Keep WordpressContext first!
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - "%paths.base%/features/wordhat/bootstrap/FeatureContext"
```
**Given** all the files are located in the `paths`.  
**And** The `FeatureContext` is in the subdirectory `%paths.base%/features/wordhat/bootstrap` directory.
**When** I run `vendor/bin/behat --config wordhat.yml --colors`
**Then** I get this error:
```
> vendor/bin/behat --config wordhat.yml --colors
In UninitializedContextEnvironment.php line 44:
  `/Users/bartonhammond/projects/twlw/wp-content/themes/jumpoff/features/wordhat/bootstrap/FeatureContext` context class not found and can not be used.  
```

**Given** the error above 
**When** I `cat` file that is reported as `not found`
**Then** I see
```
$ cat /Users/bartonhammond/projects/twlw/wp-content/themes/jumpoff/features/wordhat/bootstrap/FeatureContext.php
<?php
use PaulGibbs\WordpressBehatExtension\Context\RawWordpressContext;

use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Behat\Tester\Exception\PendingException;

... cut for brevity

```

**Given** I move the `FeatureContext` to `features\snapshot` 
**And** I update the Yamal as follows
```
      contexts:
        # Keep WordpressContext first!
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - FeatureContext
```
**When** I run `vendor/bin/behat --config wordhat.yml --colors`
**Then** I see
```
6 scenarios (6 passed)
27 steps (27 passed)
0m24.18s (13.88Mb)
```

**But** I want the `FeatureContext` to be located in **`"%paths.base%/features/wordhat/bootstrap/FeatureContext"`**

* How do I do that?

* Also where are the specs for the Behat YAML?
