### ISSUE TITLE
Behat loops infinitely for *.scenarios files

### ISSUE THREAD

**Issue by AC-TimRourke** [Behat/Behat#1133]
As described in https://github.com/Behat/Behat/issues/1067, I am experiencing infinite looping when using a `*.scenarios` file to segment my tests.

My scenarios file looks like this:
```bash
features/path/to/some/feature1.feature
features/path/to/some/feature2.feature
```

Running Behat like this:
```bash
vendor/bin/behat path/to/my/scenariosfile.scenarios
```

Behat loops indefinitely, rerunning the same tests over and over again. I have to manually terminate the process by pressing Ctrl-C.

Behat version: v3.4.3

I see that you closed the issue I referenced above for insufficient information. If this is not sufficient information to investigate, please let me know what else I can provide. Thanks!

**Comment by AC-TimRourke** [comment]
PHP version in my testing environment is:

```bash
# php --version
PHP 5.6.31 (cli) (built: Oct 10 2017 02:22:55)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by keepMoh** [comment]
I have experienced the same problem, and i have found out what caused that !

My behat.yml file contains configuration for several suites, when I switch back to old default configuration without custom suites, it stops looping "infinitely".

Now let me give some informations about my Symfony project : 
php : 7.1.4
behat/behat                          v3.5.0             Scenario-oriented BDD framework for PHP 5.3
behat/gherkin                        v4.5.1             Gherkin DSL parser for PHP 5.3
behat/mink                           v1.7.1             Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver         1.3.3              Symfony2 BrowserKit driver for Mink framework
behat/mink-extension                 2.3.1              Mink extension for Behat
behat/mink-selenium2-driver          v1.3.0             Selenium2 (WebDriver) driver for Mink framework
behat/symfony2-extension             2.1.4              Symfony2 framework extension for Behat
behat/transliterator                 v1.2.0             String transliterator

That problem happened too when behat/behat was v3.4.3 like  AC-TimRourke.


My behat.yml configuration for suites looks like  :
```
    suites:
        suite1:
            paths: [ '%paths.base%/features/software/Suite1' ]
            contexts:
                - FirstContext
                - SecondContext
                - ThirdContext
        suite2:
            paths: [ '%paths.base%/features/software/Suite2' ]
            contexts:
                - FirstContext
                - SecondContext
                - ThirdContext
        suite3:
            paths: [ '%paths.base%/features/software/Suite3' ]
            contexts:
                - FirstContext
                - SecondContext
                - ThirdContext
        suite..N:
            paths: [ '%paths.base%/features/software/Suite..N' ]
            contexts:
                - FirstContext
                - SecondContext
                - ThirdContext
```
And this configuration for suites caused vendor/bin/behat failed.scenarios to loop "infinitely".
But it does not seem to loop infinitely. Actually it seems to loop the number of times you have a suite configured. If i have 10 suites, it will loop 10 times.

I have modified Behat\Behat\Gherkin\Specification\Locator\FilesystemScenariosListLocator::locateSpecifications(Suite $suite, $locator) to check how many times it runs, and it ran 10 times if i had 10 suites. (I dont know if it gives a clue to you, but thats what i did to get my clues)

When I switched back to simple configuration for suites, it ran the scenarios only once as expected !
simple configuration for suites  : 
```
    suites:
        default:
            contexts:
                - FixturesContext:
                - FeatureContext:
                - TableContext:

```
What do you think about that ?
