### ISSUE TITLE
Error when implements multiple context files

### ISSUE THREAD

**Issue by JimiPedros** [Behat/Behat#1140]
Hi there, I am getting this issue when trying to use multiple context files. I have checked so many times the class names, paths, .. everything - but I don't understand how this issue is still coming up.

`  [Behat\Behat\Context\Exception\ContextNotFoundException] 'src/suites/0_global_setup/GlobalSetupContext' context class not foun
  d and can not be used.`

#### behat.yml

``` 
autoload:
    '': src/context_base

  suites:

    global_setup:
    # Description: This feature will test Login functionality
      paths:
        - src/suites/0_global_setup
      contexts:
        - src/suites/0_global_setup/GlobalSetupContext


    account_setup:
    # Description: This feature will test Login functionality
      paths:
        - src/suites/1_account_setup
      contexts:
        - src/suites/1_account_setup/AccountSetupContext
```

#### Project Dir

![screen shot 2018-04-09 at 1 38 21 pm](https://user-images.githubusercontent.com/9257646/38475300-54639b0e-3bfb-11e8-8db2-5b864a5ea817.png)

Thanks for any help!
