### ISSUE TITLE
--tags="@tag1&&@tag2" execute scenarios with only one of the tags

### ISSUE THREAD

**Issue by netraagal** [Behat/Behat#1141]
Hi,
I had this issue from a long time but it wasn't a problem since then

### My first test

Firstly, I have 2 suites
```
default:
     suites:
          website1: // all Features have @website1 tag
              contexts: [...]
              paths: [...]
          website2: // all Features have @website2 tag
              contexts: [...]
              paths: [...]
```
and some Scenarios have @error tag if they are are not actually ok

And I launch my Scenarios like this:
```
vendor\bin\behat --tags '~@error&&@website1'
```
to test the first website Scenarios, without the @error Scenarios as I know they will not be ok.

Sadly, My result is not what I want...
Behat seems to launch **firstly** all Scenario with no the @error tag and don't take in account the @website1 tag.

So there is also Scenario with @website2 tag which are launched...

### the second test

My `.feature` files are like this
```
| -- website1 //all scenarios bellow have @website1 tag
     | -- front //all scenarios bellow have @front tag
           | -- order //all scenarios bellow have @order tag
                 | -- order.feature
           | -- connection //all scenarios bellow have @connection tag
     | -- back //all scenarios bellow have @back tag
```

to test a specific Scenario, I launch 
```
vendor\bin\behat --tags '@website1&&@front&&@order'
```
and all Scenarios with @website1 tag are launched

### So...

Is it a normal behaviour ? I have to precise the more specific tag firstly everytime, and for the ~@tag it's really annoying.

In the documentation <a href="http://docs.behat.org/en/v2.5/guides/6.cli.html#gherkin-filters">here</a>, it say the **AND** is inclusive:

> `behat --tags '@orm&&@fixtures'` will run only features or scenarios with both the @orm AND @fixtures tags (must have both).

Thanks in advance!
