### ISSUE TITLE
Call to a member function getURL() on null.  Session not started?

### ISSUE THREAD

**Issue by bartonhammond** [Behat/Behat#1168]
I did some refactoring of my code and broke the execution.  Not sure what happened.  Any way...

When I run this `behat.yml`:
```
default:
  autoload:
    '': "%paths.base%/../bootstrap"  
  suites:
    mobile:
      paths: ["%paths.base%/../temp/pro_mobile.feature"]      
      contexts:
        - ThinkWellContext:
            - 2018-08-16-16-53
            - Nexus9-And60
            - MblChrome63

  extensions:
    Behat\MinkExtension:
      default_session: selenium2
      browser_name: chrome
      base_url: https://twlwdev.wpengine.com               
      selenium2:
        wd_host: https://userid/password@crossbrowsertesting.com/wd/hub
        capabilities:
          name: "TWLW"
          extra_capabilities:
            os_api_name: Nexus9-And60
            browser_api_name: MblChrome63
            
            build: 1.0.0
            record_video: true
            record_network: true
            max_duration: 14400
            new_command_timeout: 14400

    SensioLabs\Behat\PageObjectExtension:
      namespaces:
        page: [pages]
        element: [pages]
```

I get this error.  Note: this `FeatureContext` code use to work.  I don't understand why it is failing now.
```
vendor/bin/behat --config /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/features/cbt/behat-cbt.yml
Feature: Pro Mobile
  Register with a Free Account
  Select a Free program
  Listen to the free program
  I provide "@sizeMobile" for Scenario for local mobile emulation
  I provide "@snapshot" for Scenario to capture screen shots

PHP Fatal error:  Uncaught Error: Call to a member function getURL() on null in /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/vendor/wisnet/behatpom/src/behatPOM/FeatureContext.php:119
Stack trace:
#0 /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/vendor/wisnet/behatpom/src/behatPOM/FeatureContext.php(205): Wisnet\BehatPom\FeatureContext->checkIfRunningOnCbt()
#1 /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/Initializer/MinkAwareInitializer.php(53): Wisnet\BehatPom\FeatureContext->setMink(Object(Behat\Mink\Mink))
#2 /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/vendor/behat/behat/src/Behat/Behat/Context/ContextFactory.php(147): Behat\MinkExtension\Context\Initializer\MinkAwareInitializer->initializeContext(Object(ThinkwellContext))
#3 /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/vendor/behat/behat/src/Behat/Behat/Context/Cont in /Users/bartonhammond/projects/thinkwell-livewell/wp-content/themes/jumpoff/vendor/wisnet/behatpom/src/behatPOM/FeatureContext.php on line 119

```
The `FeatureContext` is loaded fine.  It appears that the "gherkin" is also.

Here is PsyShell interaction within `FeatureContext`.  The $driver is not started. 
```
Psy Shell v0.8.18 (PHP 7.1.16 — cli) by Justin Hileman
New version is available (current: v0.8.18, latest: v0.9.7)

From vendor/wisnet/behatpom/src/behatPOM/FeatureContext.php:119:

    117|         $session = self::$mink->getSession('selenium2');
    118|         $driver = $session->getDriver();
  > 119|         eval(\Psy\sh());
    120|         $webDriverSession = $driver->getWebDriverSession();
    121|         $url = $webDriverSession->getURL();

>>> $driver
=> Behat\Mink\Driver\Selenium2Driver {#1956}
>>> $driver->isStarted()
=> false
>>>  $driver->getWebDriverSession();
=> null
```
Any idea on how to debug this?  Thanks!
