### ISSUE TITLE
FeatureContext kernel: @kernel context class not found and can not be used

### ISSUE THREAD

**Issue by PaddyLock** [Behat/Behat#1177]
I am using Symfony 4. here is my config

```
default:
    suites:
        default:
            contexts:
                - FeatureContext
                    kernel: '@kernel'
                - Behat\MinkExtension\Context\MinkContext
    extensions:
        Behat\Symfony2Extension:
            kernel:
                bootstrap: features/bootstrap/bootstrap.php
                class: App\Kernel
        Behat\MinkExtension:
            base_url: 'https://localhost/app_test.php/'
            sessions:
                default_session:
                    symfony2: ~
            selenium2: ~
            show_cmd: 'open %s'
            files_path: '/tmp/'
            browser_name: 'chrome'


    # In this instance, scenarios tagged as @friday and @weekend will be ignored unless the CLI command is run with filter to include them
    gherkin:
        filters:
            tags: ~@friday&&~@weekend
```

I get the following error when I run behat

` `FeatureContext kernel: '@kernel'` context class not found and can not be used.`

What does this mean please?

**Comment by jakzal** [comment]
You seem to have missed the `:` after `FeatureContext`. 

```yaml
default:
    suites:
        default:
            contexts:
                - FeatureContext:
                     kernel: '@kernel'
```
