### ISSUE TITLE
"Serialization of 'Closure' is not allowed event" error with v3.5.0

### ISSUE THREAD

**Issue by clement-michelet** [Behat/Behat#1181]
The fix from PR #1163 doesn't work even with v3.5.0.
Rolling back to symfony/dependency-injection v3.4.17 fix the bug

Packages :
- behat/behat v3.5.0
- behat/mink v1.7.1
- pavlakis/slim-behat-extension v1.0.2
- symfony/dependency-injection v4.1.6

behat.yml

```yml
default:
  autoload:
    '': '%paths.base%/tests/Functional/Bootstrap'
  suites:
    default:
      paths:
      - '%paths.base%/tests/Functional/Features'
      contexts:
      - Vendor\Test\Functional\Bootstrap\DummyContext
  extensions:
    Pavlakis\Slim\Behat:
      config_file: ./config/settings.php
      dependencies_file: ./config/dependencies.php
      middleware_file: ./config/middleware.php
      routes_file: ./config/routes.php
```

Running vendor/bin/behat --config behat.yml -vvv produce the following errors :

```bash
In RemoveUnusedDefinitionsPass.php line 75:
                                             
  [Exception]                                
  Serialization of 'Closure' is not allowed  
                                             

Exception trace:
 serialize() at /var/www/html/vendor/symfony/dependency-injection/Compiler/RemoveUnusedDefinitionsPass.php:75
 Symfony\Component\DependencyInjection\Compiler\RemoveUnusedDefinitionsPass->process() at /var/www/html/vendor/symfony/dependency-injection/Compiler/RepeatedPass.php:57
 Symfony\Component\DependencyInjection\Compiler\RepeatedPass->process() at /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php:746
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/www/html/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:187
 Behat\Testwork\Cli\Application->createContainer() at /var/www/html/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:161
 Behat\Testwork\Cli\Application->createCommand() at /var/www/html/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:122
 Behat\Testwork\Cli\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/behat/behat/bin/behat:34
```
