### ISSUE TITLE
Is it not possible to share a step between contexts?

### ISSUE THREAD

**Issue by letharion** [Behat/Behat#1188]
https://github.com/Behat/Behat/issues/924 and https://github.com/Behat/Behat/issues/558 appear relevant, so I already have an inkling that this is not supported, but I'm not entirely sure, so I'm asking anyway.

Can I share a step like `Data should be JSON` in a base class (or similar approach?) between two different test classes? Currently when both those classes inherit from the same base, I get an error that the Step has been implemented multiple times.

Very terse example of what I'm trying to do:
```
class Test1 extends Base {
  /** @Given I do thing */
  function a() {
    $this->data = [];
  }
}
class Test2 extends Base {
  /** @Given I do thing */
  function a() {
    $this->data = (object)[];
  }
}
class Base implements Context {
  /** @Then Data should be json */
  function shouldBeJson() {
    $data = json_decode($this->data);
  }
}
```

**Comment by stof** [comment]
Well, if you register the 2 context classes in the same suite, you cannot have the definition of the same step in both classes (be it through inheritance from a parent class or from explicit declaration in the class), as that would be ambiguous (Behat would not know which context it should use when calling the method).

if your 2 contexts are used in different suites, both are fine. Behat does not care where the methods are defined. It cares about having only one definition for each step among registered contexts.

**Comment by letharion** [comment]
So I switched the suites around so my two sub classes are now in separate suites:
```
default:                                                                                                                                                                                                        
  suites:                                                                                                                                                                                                       
    Hello:                                                                                                                                                                                                      
      contexts:                                                                                                                                                                                                 
        - HelloFeatureContext:                                                                                                                                                                                  
          - say: 'hello'                                                                                                                                                                                        
    World:                                                                                                                                                                                                      
      contexts:                                                                                                                                                                                                 
        - WorldFeatureContext:                                                                                                                                                                                  
          - say: 'world' 
```

However, then I get the opposite problem instead, where Behat considers the World specific functions missing from the Hello feature, even though they are not used there.

```
$ cat features/Hello.feature 
Feature: Test Hello

  Scenario:
    Given I say "hello"
    Then I should say hello
```

```
$ cat features/World.feature 
Feature: Test world

  Scenario:
    Given I say "world"
    Then I should say world
```

```
$ cat features/bootstrap/HelloFeatureContext.php 
<?php
use Behat\Behat\Context\Context;
class HelloFeatureContext extends FeatureContext {
    public function __construct($say) {
        parent::__construct($say);
    }

    /**
     * @Then I should say hello
     */
    public function iShouldSay() {
        echo "hello";
    }
}
```

```
$ cat features/bootstrap/WorldFeatureContext.php 
<?php
use Behat\Behat\Context\Context;
class WorldFeatureContext extends FeatureContext {
    public function __construct($base_uri) {
        parent::__construct($base_uri);
    }

    /**
     * @Then I should say world
     */
    public function iShouldSay() {
        echo "world";
    }
}
```

```
$ cat features/bootstrap/FeatureContext.php 
<?php
use Behat\Behat\Context\Context;

/**
 * Features context.
 */
class FeatureContext implements Context {
    public function __construct(array $parameters) {
        var_dump($parameters['say']);
    }

    /**
     * @Given I say :arg1
     **/
    public function iSay($arg1) {
        echo $arg1;
    }
}
```

The above yields:
```
--- HelloFeatureContext has missing steps. Define them with these snippets:

    /**
     * @Then I should say world
     */
    public function iShouldSayWorld()
    {
        throw new PendingException();
    }

--- WorldFeatureContext has missing steps. Define them with these snippets:

    /**
     * @Then I should say hello
     */
    public function iShouldSayHello()
    {
        throw new PendingException();
    }
```
