### ISSUE TITLE
Unrecognized option "filters" under "testwork"

### ISSUE THREAD

**Issue by tysonnero** [Behat/Behat#1213]
Can anyone spot what I'm doing wrong in my `behat.yml`?

I'm getting this error:
```
Unrecognized option "filters" under "testwork". Available options are "api_extension", "argument", "autoload", "calls", "cli", "contexts", "definitions", "environments", "events", "exceptions", "filesystem", "formatters", "gherkin", "gherkin_translations", "helper_container", "hooks", "ordering", "snippets", "specifications", "suites", "testers", "transformations", "translation".  
```

with the following config:
```
ci:
    filters:
        tags: "~@ignore"
    extensions:
        Imbo\BehatApiExtension:
            apiClient:
                base_uri: https://localhost:443
```

**Comment by jakzal** [comment]
`filters` are defined at a test suite level:

```
ci:
  suites:
    default:
      filters:
        tags: "~@ignore"
```

You're probably reading docs for [Behat 2.x](http://docs.behat.org/en/v2.5/guides/7.config.html#filters) instead of [Behat 3.x](http://behat.org/en/latest/user_guide/configuration/suites.html#suite-filters).
