### ISSUE TITLE
Allowed memory size of 2147483648 bytes exhausted in Travis CI

### ISSUE THREAD

**Issue by moneeshkoundal** [Behat/Behat#1215]
Memory limit exceed issue is coming in our Travis CI builds which do not happen on local instance.

What we have seen with each scenario the memory exceed with 120 MB and we have around 50 test cases so it takes around 5 GB of memory, for now, we have increased the memory to infinite but that is not the ideal solution as this will block us later on so need help here.

Below is our behat.yml
```
default:
  suites:
    default:
      paths:
        - %paths.base%/features
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: ${reports.localDir}
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\ConfigContext
  extensions:
    Behat\MinkExtension:
      default_session: goutte
      browser_name: chrome
      javascript_session: default
      goutte: ~
      files_path: "%paths.base%/media"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
      region_map:
        header: "header"

```

example.local.yml

```
# To generate a local.yml file using this the example template, execute:
# `blt tests:behat:init:config` from the project root.
imports:
  - behat.yml

local:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: ${repo.root}/tests/behat
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: selenium2
      # configure the base url for your site
      base_url: ${project.local.uri}
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # use the following lines to disable SSL authentication for goutte.
      # goutte:
      #   guzzle_parameters:
      #     verify: false
      selenium2:
        wd_host: ${behat.selenium.url}
        browser: chrome
        capabilities:
          chrome:
            switches:
              - "--window-size=1366,768"
              - "--no-sandbox"
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: ${docroot}
      drush:
        alias: '@self'

docksal:
  suites:
    default:
      paths:
        features: ${repo.root}/tests/behat
  extensions:
    Behat\MinkExtension:
      javascript_session: selenium2
      base_url: http://web
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities:
          chrome:
            switches:
              - "--window-size=1366,768"
              - "--no-sandbox"

```
