### ISSUE TITLE
Run tests in multiple browsers

### ISSUE THREAD

**Issue by p2635** [Behat/Behat#1222]
Can someone help me? I'm trying to set up Behat to run tests in multiple browsers. Whether they run at the same time or one after another, it doesn't matter.

My yml file looks like this but when I actually try to run it, it only runs in firefox? Please let me know if you need more info. This issue is possibly related to #629.
```
# behat.yml
default:
  suites:
    default:
      filters:
        tags: "~@manual_test_only"
  autoload:
    '': %paths.base%/features/bootstrap
  extensions:
      Behat\MinkExtension:
        files_path: './features/tests/adverts/assets/images'
        sessions:
          firefox:
            selenium2:
              browser: firefox
              capabilities:
                extra_capabilities:
                  acceptInsecureCerts: true
                  marionette: false
          chrome:
            selenium2:
              browser: chrome
              capabilities: { "browserName": "chrome", "browser": "chrome", "version": "62", 'chrome': {'switches':['--no-sandbox']}}
```
