### ISSUE TITLE
Merging of 'default' configuration is inconsistent with merging of profile configuration in general

### ISSUE THREAD

**Issue by func0der** [Behat/Behat#1224]
The configuration merged behaves differently depending on the profile you load.

`behat.basic.yml`
```yaml
default:
  extensions:
    Behat\MinkExtension:
      browser_stack:
        capabilities:
          browserstack-tunnel: true
```

`behat.production.yml`:
```yaml
imports:
  - behat.basic.yml
default:
  extensions:
    Behat\MinkExtension:
      browser_stack:
        capabilities:
          browserstack-tunnel: false
chrome:
  extensions:
    Behat\MinkExtension:
      browser_stack:
        capabilities:
          browserstack-debug: true
```

Running `behat --profile=default`
Expected:
```yaml
browserstack-tunnel: false
```

Is:
```yaml
browserstack-tunnel: false
```

Running `behat --profile=chrome`

Expected:
```yaml
browserstack-debug: true
browserstack-tunnel: false
```

Is:
```yaml
browserstack-debug: true
browserstack-tunnel: true // <- this should be FALSE
```

I find this an inconsistency in the configuration merging. I thought this would have been addressed in #230, but it seems that the fix was only for the calling of the specific profile.
