### ISSUE TITLE
Get trace log.

### ISSUE THREAD

**Issue by Ghostff** [Behat/Behat#1228]
I made an issue [HERE](https://github.com/mozilla/geckodriver/issues/1548#issuecomment-502351401) on how Firefox is failing on my tests, and they required a trace log and since in don't have an in dept knowledge of how Behat works, am wondering if there is a way to get Firefox trace log?

**Comment by FroggDev** [comment]
Version: v0.25.0
Platform: Windows
Firefox: 68.0.1esr (64 bits)
Selenium: 3.141.59

Mink\Session is empty to page is empty so nothing is found.

When i use $this->assertSession()->elementsCount i get the same error, but in the stack Selenium2Driver seems to have the informations :
       # FeatureContext::iLogin()
      0 elements matching css "input[name="MAIL"]" found on the page, but should be 1.

      +--[ https://xxxx/login | Selenium2Driver ]
      |
      |  <body>
      |
      |  <div class="header">
      |         <div class="logo">
      |                 <a href="#" title="xxx"><img src="/ident/img/xxx.png" alt="xxx"></a>
      |         </div>
      |
      |         <div class="acces_top">
      |                 <a class="btnt_identify" href="/login"><span>Identifiez-vous</span></a>
      |         </div>
      |  </div>
      |  <div class="menu">
      |         <div class="sep"></div>
      |  </div>
      |  <div class="site">
      |
      |                 <div class="page_auth">
      |                         <div class="page_auth_content">
      |                                 <h1 style="color:#b90d0c">Identifiez-vous</h1>
      |                                 <form enctype="application/x-www-form-urlencoded" action="/login" method="post">
      |                                                                                 <br>
      |
      |                                         <fieldset>
      |                                                 <label>Mon adresse email</label>
      |                                                 <p class="champ-cont"><span class="input-cont">
      |                                                         <input class="champ" type="text" name="MAIL" value="">
      |                                                 </span></p>
      |                                         </fieldset>

**Comment by gregatpega** [comment]
@Ghostff to enable the trace-level log in the geckodriver you should set `moz:firefoxOptions` as it is described in https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html article.
It means that you should extend your **behat.yml** file by adding `extra_capabilities` as follows:

```yaml
firefox:
  extensions:
    Behat\MinkExtension:
      base_url: https://www.wikipedia.org/
      browser_name: firefox
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
        browser: firefox
        capabilities:
          marionette: true
          extra_capabilities:
            moz:firefoxOptions:
              log:
                level: trace
```
When you rerun the scenario with such configuration you should see some trace messages in your **log.txt** file, for example:
```
1572470910369	Marionette	TRACE	Received observer notification profile-after-change
1572470910491	Marionette	TRACE	Received observer notification command-line-startup
1572470910491	Marionette	TRACE	Received observer notification nsPref:changed
```
