### ISSUE TITLE
Multiple base urls

### ISSUE THREAD

**Issue by mihaiGreppy** [Behat/Behat#1233]
Hi. Is there a way of using two base urls? I need to check the interaction between an admin url and the public one. So in the middle of the test I need to switch between them. Is there a solution for it without using Mink?

**Comment by stof** [comment]
Base urls for what ? Behat does not deal with URLs at all.

**Comment by Truptii** [comment]
You can try using 2 profiles in behat.yml and execute the scenarios in the sequence you want with the help of profiles

**Comment by janipalsamaki** [comment]
This example requires Mink, but might be worth sharing.

Define the base URL as usual. Define the additional base URL as a context parameter:

`behat.yml`:

```yml
default:
  suites:
    default:
      contexts:
        - FeatureContext:
            parameters:
              admin_base_url: https://admin.example.com/
      filters: ~
  extensions:
    Behat\MinkExtension:
      goutte:
        guzzle_parameters:
          verify: false
      selenium2:
        browser: chrome
        capabilities: { "browser": "chrome", "version": "*", "marionette": true, "extra_capabilities": { "chromeOptions": { "w3c": false } } }
      base_url: https://public.example.com/
```

`FeatureContext.php`:

Store the context parameters for easy access:

```php
class FeatureContext extends Behat\MinkExtension\Context\MinkContext {

  /** @var array */
  private $contextParameters;

  public function __construct($parameters) {
      $this->contextParameters = $parameters;
   .  ..
```

Define a custom step for switching the base URL:

```php
  /**
   * @Given I am on admin homepage
   */
  public function iAmOnAdminHomepage() {
    $this->setMinkParameter('base_url', $this->contextParameters['admin_base_url']);
    $this->iAmOnHomepage();
  }
```

Use the custom step in your scenario to switch the base URL.
