### ISSUE TITLE
Behat don't run on gitlab CI.

### ISSUE THREAD

**Issue by Nebojsaa** [Behat/Behat#1240]
We are using gitlab CI and trying to use Behat on top of it. 
This is how our gitlab-ci.yml looks like - 
`Set any variables we need`
`variables:`
   ```
 CHROME_DEBUG_URL: http://localhost:9222
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE: sity_dev
    MYSQL_ROOT_PASSWORD: root
    # Remove variables MYSQL_USER and MYSQL_PASSWORD above if you like to login as root user
    MYSQL_USER: user
    MYSQL_PASSWORD: userpass
    APP_ENV: dev
```

```
Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
services:
    - name: mysql:5.7.21
      alias: mysql
```

```
stages:
    - test

php-test:
    stage: test
    image: php:7.1-fpm-jessie
    before_script:
        # Setup php.ini
        - cp docker-symfony/php7-fpm/memory-limit-php.ini /usr/local/etc/php/conf.d/memory-limit-php.ini
        - cp docker-symfony/php7-fpm/max_input_vars-php.ini /usr/local/etc/php/conf.d/max_input_vars-php.ini
        - cp docker-symfony/php7-fpm/max_execution_time-php.ini /usr/local/etc/php/conf.d/max_execution_time-php.ini
        - cp docker-symfony/php7-fpm/request_terminate_timeout-php.ini /usr/local/etc/php/conf.d/request_terminate_timeout-php.ini
        # Install libs
        - apt-get update
        - apt-get install lsof -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libzip-dev libmagickwand-dev libmagickcore-dev
        # Install PHP extensions
        - docker-php-ext-install pdo pdo_mysql curl json intl gd xml zip bz2 opcache pcntl shmop
        # Install & enable imagick & apcu
        - pecl install imagick
        - pecl install APCu-5.1.8
        - docker-php-ext-enable apcu imagick
        # Install and run Composer
        - curl -sS https://getcomposer.org/installer | php
        - php composer.phar install
        - echo "All vendors are installed!"
        # Create & load data in DB -> used doctrine
        - php app/console doctrine:schema:update --force
        - php app/console doctrine:fixtures:load --no-interaction
        # Install nginx
        - apt-get install -y nginx
        - cp docker-symfony/nginx/server.conf /etc/nginx/sites-enabled/default
        # Install chrome-headless
        - apt-get update
        - apt-get install -y gettext-base
        - apt-cache search wget
        - apt-get install -y wget
        - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
```
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        - set -x
        - apt-get update
        - apt-get install -y xvfb google-chrome-stable
        - wget -q -O /usr/bin/xvfb-chrome https://bitbucket.org/atlassian/docker-node-chrome-firefox/raw/ff180e2f16ea8639d4ca4a3abb0017ee23c2836c/scripts/xvfb-chrome
        - ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome
        - chmod 755 /usr/bin/google-chrome
        - /usr/bin/google-chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox --window-size="1920,1080" --disable-dev-shm-usage --no-startup-window --no-first-run --no-pings &
        # Install pip, yq & jq -> Needed for backstop:config
        - apt install -y python-pip
        - pip install -y yq
        - wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
        - chmod +x jq-linux64
        - mv jq-linux64 $(which jq)
        # Install nodejs
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get update
        - apt-get install -my nodejs
        - npm i
        - npm run gulp-build
    script:
        # Run php-fpm service
        - sed -i -e 's/daemonize = no/daemonize = yes/g' /usr/local/etc/php-fpm.d/zz-docker.conf
        - php-fpm
        # Start nginx service
        - php app/console cache:clear --env=prod
        - service nginx start
        - echo "Everything fine!"
        - mkdir behat_screenshots
        - chmod 777 behat_screenshots
        - export BEHAT_SCREENSHOTS="1"
        - bin/behat --init
        - bin/behat --colors
        # Start backstop js tests
        - echo "BeackstopJS tests start"
        - npm run backstop:config:continuous
        - npm run backstop:test
        - npm run backstop:config:parallel
        - npm run backstop:test
        - echo "Done!"`
Then Behat.yml and this is how it looks like - 
```
default:
    autoload:
        '': src/Sity/AppBundle/Features/Context

```
    suites:
        default:
            # Timeout params are in seconds
            contexts:
                -   Sity\AppBundle\Features\Context\FeatureContext:
                        lang: 'single'
                        appUrl: 'http://localhost'
                        testCompanyId: 1
                        screenshotPath: 'screenshots/behat'
                        globalTimeout: 15
                        renderTimeout: 5
                        apiResponseTimeout: 360
                -   Sity\AppBundle\Features\Context\GroupContext:
                -   Sity\AppBundle\Features\Context\MediaContext:
                -   Sity\AppBundle\Features\Context\PageContext:
                -   Sity\AppBundle\Features\Context\PagePartContext:
                -   Sity\AppBundle\Features\Context\RoleContext:
                -   Sity\AppBundle\Features\Context\UserContext:
                -   Sity\AppBundle\Features\Context\RegionContext:
            bundle: 'SityAppBundle'
            type: symfony_bundle
            paths:
                - src/Sity/AppBundle/Features/Test

    formatters:
        pretty: true

    extensions:
        DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
        Behat\Symfony2Extension:
            kernel:
                env: test
                debug: true
        Behat\MinkExtension:
            browser_name: chrome
            base_url: 'http://localhost:9222'
            default_session: default
            javascript_session: default
            selenium2: ~
            files_path: src/Sity/AppBundle/Features/Media/
            show_cmd: 'chrome %s'
            sessions:
                default:
                    chrome:
                        api_url: 'http://localhost:9222'
                        download_behavior: allow
                        download_path: /code/dw/
                        validate_certificate: false
                        socket_timeout: 30
                    
And this is the error that I get - 
  Background:                
```
# src/Sity/AppBundle/Features/Test/AdminIconWidget.feature:9
127.0.0.1 -  25/Sep/2019:12:55:54 +0000 "GET /app.php" 500
    Given I log in as "admin" # Sity\AppBundle\Features\Context\FeatureContext::iLogInAs()
      Button with id|name|title|alt|value "_submit" not found. (Behat\Mink\Exception\ElementNotFoundException)

```
Could someone answer to me what is wrong with this?
Any kind of help is really much appreciated.
