### ISSUE TITLE
File path of failed step is invisible in iTerm2 with dark theme

### ISSUE THREAD

**Issue by xorik** [Behat/Behat#1268]
Hi.

Behat 3.5.0, iTerm2 3.3.6, MacOS 10.14.6
If I choose any dark iTerm theme (e.g. Tango Dark), then path of a failed scenario is invisible, unless I select it.

![Screenshot 2020-01-14 at 16 51 45](https://user-images.githubusercontent.com/347044/72359485-a8c7bc80-36ee-11ea-98f2-2e080a86647c.png)
![Screenshot 2020-01-14 at 16 52 10](https://user-images.githubusercontent.com/347044/72359507-b2512480-36ee-11ea-9eea-2800b69aa5df.png)

On light themes everything is okay:
![Screenshot 2020-01-14 at 16 56 32](https://user-images.githubusercontent.com/347044/72359607-ddd40f00-36ee-11ea-840b-4f69681bcceb.png)

**Comment by mpdude** [comment]
I guess you should try one of the many great color profiles in iTerm2 :-) 

Not sure if this can be fixed here

**Comment by xorik** [comment]
@mpdude maybe change the color? Not a critical issue, you could close it :)

**Comment by masterjus** [comment]
@xorik You could set colors in your `behat.yml`:
```yaml
default:
  formatters:
    progress:
      output_styles:
        comment: [ black, white, [ underscore ] ]

```
