### ISSUE TITLE
Learning Behat on a Drupal 8.9 site

### ISSUE THREAD

**Issue by jtjones3** [Behat/Behat#1320]
When I start with  `vendor/bin/behat -dl` I get the following error message In `ExtensionManager.php line 194: `DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension` extension file or class could not be located. `.

**Behat.yml**:
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
  gherkin:
    cache: ~
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      goutte: ~
      base_url: http://a26.docksal
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: drupal
      drupal:
        drupal_root: web/
      region_map:
        header: "#header"
        sidebar: "#sidebar-first"
        content: "#content"
        footer: ".site-footer"
```

Composer.json:
```
  "require-dev": {
    "mikey179/vfsstream": "^1.2",
    "behat/behat": "3.*",
    "behat/mink": "^1.7",
    "behat/mink-extension": "^2.2",
    "behat/mink-goutte-driver": "^1.2",
    "jcalderonzumba/gastonjs": "^1.0.2",
    "jcalderonzumba/mink-phantomjs-driver": "^0.3.1",
    "drupal/drupal-extension": "^3.1",
    "drush-ops/behat-drush-endpoint": "^0.0.4",
    "pantheon-systems/quicksilver-pushback": "~1",
    "phpunit/phpunit": "^6.0",
    "symfony/css-selector": "^3.0"
  },
```
Thanks for any assistance
