### ISSUE TITLE
Add GPG signature to PHAR files in releases

### ISSUE THREAD

**Issue by hollodotme** [Behat/Behat#1331]
## Why?

The https://phar.io project and its installer `phive` allows to manage and install PHAR tools from the PHP eco system from sources like GitHub releases.

The main goal of this project is to install only verified software.
This is achieved by verifying the downloaded software against their GPG signatures and a confirmation by the user to trust the GPG key of the author.

Have a look at the list of other PHAR tools that have GPG signatures: https://phar.io/#Tools

## How?

There is a guide on how to add the GPG signature to GitHub releases to make a PHAR release installable via `phive`, see: https://phar.io/howto/sign-and-upload-to-github.html

The following modifications in the `.github/workflows/build.yml` should do the job to create & upload the signature, once a GPG key was added to the GitHub secrets of the project:

Edited `.github/workflows/build.yml` (see comments)
```yml
name: Build

on:
    push:
        branches: [master]
    pull_request:
    release:
        types: [created]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   php: 7.2
                        publish-phar: true
                    -   php: 7.2
                        skip-interop: true
                    -   php: 7.2
                        composer-flags: --prefer-lowest
                    -   php: 7.3
                    -   php: 7.4
                    -   php: 7.4
                        symfony-version: ^4.4
                    -   php: 8.0

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    ini-values: "phar.readonly=0,zend.exception_ignore_args=Off"
                    coverage: none

            -   name: Update Symfony version
                if: matrix.symfony-version != ''
                run: composer require --no-update "symfony/symfony:${{ matrix.symfony-version }}"

            -   name: Uninstall container interop
                if: matrix.skip-interop
                run: composer remove --dev --no-update container-interop/container-interop

            -   name: Install dependencies
                run: composer update ${{ matrix.composer-flags }}

            -   name: Run tests (phpunit)
                run: ./vendor/bin/phpunit

            -   name: Run tests (Behat)
                run: ./bin/behat -fprogress --strict $([ -z "${{ matrix.skip-interop }}" ] || echo "--tags ~@interop&&~@php8")

            -   name: Run tests (Behat for PHP 8.0)
                if: matrix.php >= 8.0
                run: ./bin/behat -fprogress --strict --tags=@php8

            -   name: Build the PHAR
                if: matrix.php != '8.0'
                run: |
                    curl -LSs https://box-project.github.io/box2/installer.php | php &&
                    export PATH=.:$PATH &&
                    rm -Rf ./vendor &&
                    composer install --no-dev -o &&
                    box.phar build

            # Add step to generate GPG signature for behat.phar
            # Replace "team@behat.org" and "<NAME_OF_GPG_KEY_SECRET>" with appropriate values

            - name: Create GPG signature of PHAR
              if: matrix.publish-phar
              run: |
                  mkdir -p ~/.gnupg/
                  chmod 0700 ~/.gnupg/
                  echo "$GPG_SIGNING_KEY" > ~/.gnupg/private.key
                  gpg --import ~/.gnupg/private.key
                  gpg -u team@behat.org --detach-sign --output behat.phar.asc behat.phar
              env:
                  GPG_SIGNING_KEY: ${{ secrets.<NAME_OF_GPG_KEY_SECRET> }}

            -   uses: actions/upload-artifact@v1
                name: Publish the PHAR
                if: matrix.publish-phar
                with:
                    name: behat.phar

                    # Add behat.phar.asc to artifacts

                    path: |
                        behat.phar
                        behat.phar.asc

    publish-phar:
        runs-on: ubuntu-latest
        name: Publish the PHAR
        needs: tests
        if: github.event_name == 'release'
        steps:
            -   uses: actions/download-artifact@v1
                with:
                    name: behat.phar
                    path: .
            -   name: Upload behat.phar
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: behat.phar
                    asset_name: behat.phar
                    asset_content_type: application/zip

            # Add step to upload GPG signature to release

            -   name: Upload behat.phar.asc
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: behat.phar.asc
                    asset_name: behat.phar.asc
                    asset_content_type: application/octet-stream
```

You can also have a look into the workflow of the composer.phar release, they use the same solution as proposed.
See: https://github.com/composer/composer/commit/44dc3c27aacb9fcd8869b5295ebcea47bc05951c
