### ISSUE TITLE
Non-standard features path support in Behat 2.4.0 

### ISSUE THREAD

**Issue by ulrichsg** [Behat/Behat#137]
I have my features under test/behat/ rather than features/ due to project conventions. To point Behat at the correct path, I have a config/behat.yml with the following content:

```yaml
default:
  paths:
    features:  '%%BEHAT_BASE_PATH%%'
    bootstrap: '%behat.paths.features%/bootstrap'
```

and I invoke Behat with the following command:

bin/behat -c config/behat.yml test/behat/

This works in Behat 2.3.5, but in 2.4.0 I get a "Context class not found" error.
