### ISSUE TITLE
Getting Junit duration listener error

### ISSUE THREAD

**Issue by samiullah** [Behat/Behat#1385]
```
PHP Fatal error:  Declaration of Behat\Behat\Output\Node\EventListener\JUnit\JUnitDurationListener::listenEvent(Behat\Testwork\Output\Formatter $formatter, Behat\Testwork\Event\Event $event, $eventName) must be compatible with Behat\Testwork\Output\Node\EventListener\EventListener::listenEvent(Behat\Testwork\Output\Formatter $formatter, Symfony\Component\EventDispatcher\Event $event, $eventName) in C:\xampp\htdocs\corporate\docroot\vendor\behat\behat\src\Behat\Behat\Output\Node\EventListener\JUnit\JUnitDurationListener.php on line 24

Fatal error: Declaration of Behat\Behat\Output\Node\EventListener\JUnit\JUnitDurationListener::listenEvent(Behat\Testwork\Output\Formatter $formatter, Behat\Testwork\Event\Event $event, $eventName) must be compatible with Behat\Testwork\Output\Node\EventListener\EventListener::listenEvent(Behat\Testwork\Output\Formatter $formatter, Symfony\Component\EventDispatcher\Event $event, $eventName) in C:\xampp\htdocs\corporate\docroot\vendor\behat\behat\src\Behat\Behat\Output\Node\EventListener\JUnit\JUnitDurationListener.php on line 24
```

my composer.json
```
{
    "require-dev": {
        "roydude/behat-html-formatter": "^0.1.0",
        "bex/behat-screenshot": "^2.1"
    },
    "require": {
        "emuse/behat-html-formatter": "^0.1.0",
        "behat/mink-extension": "^2.3",
        "behat/mink-goutte-driver": "^1.0",
        "behat/mink-selenium2-driver": "^1.5",
        "drupal/drupal-extension": "^4.1",
        "behat/behat": "3.8.1"
    }
}


```

Behat.yml
```

default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - emuse\BehatHTMLFormatter\Context\ScreenshotContext:
            screenshotDir: report/html/behat/assets/screenshots
  formatters:
    html:
      output_path: "%paths.base%/build/html/behat"
  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: index
      print_args: true
      print_outp: true

    Behat\MinkExtension:
        browser_name: 'chrome'
#        goutte: ~
        javascript_session: selenium2
        selenium2:
          wd_host: http://127.0.0.1:4444/wd/hub
          #capabilities: { "version": "*", 'chrome': {'switches':['--start-maximized']},"extra_capabilities": {"w3c":"false"}}
          capabilities:
            chrome:
              switches:
                - "--start-maximized"
            extra_capabilities:
              goog:chromeOptions:
                w3c: false

        base_url: 'http://localhost/corporate/docroot/'
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: drupal
      drupal:
        drupal_root: C:\xampp\htdocs\corporate\docroot
#    Bex\Behat\ScreenshotExtension:
#      screenshot_taking_mode: failed_scenarios
#      image_drivers:
#        local:
#          screenshot_directory: "%paths.base%/media/failed_screenshots"

```
