### ISSUE TITLE
Step/Scenario details black color

### ISSUE THREAD

**Issue by Gabb1995** [Behat/Behat#1424]
![image](https://user-images.githubusercontent.com/20728259/227168880-458cb887-739c-4692-a4ee-d572e5fc5f64.png)

I've been looking for a while on how to change the color of the comment to the right of the steps here which is in black. Seems it's not been documented, any help?

**Comment by Gabb1995** [comment]
Fixed with:
```yaml
formatters:
    progress:
        output_styles:
            comment: [ gray ]
```
