### ISSUE TITLE
Loading a bootstrap file

### ISSUE THREAD

**Issue by BlackScorp** [Behat/Behat#1610]
Hi all,

currently i try to load a bootstrap file before the tests. i would like to run it similar to phpunit.xml with the bootstrap attribute.

according to documentation you can define bootstrap paths and behat will include all php files in it. but it seems like it does not work.

at this point i just tried everything out and added everything into behat.yaml

this is what it looks like right now

```yaml
default:
  autoload:
    '': '%paths.base%/../tests/bootstrap'
  suites:
    default:
      paths:
        features: '%paths.base%/../tests/Behat/features'
        bootstrap: '%paths.base%/../tests/bootstrap'
      bootstrap: '%paths.base%/../tests/bootstrap'
      contexts:
        - Mollie\Behat\FeatureContext
        - Mollie\Behat\ShopwareContext
```

the features path is correct, i can see my feature description. the context classes are loaded over composer and working as well. 

all i need to include one bootstrap file. when i add the part from my bootstrap file into @BeforeSuite function, everything is working fine. but i would like to include a php file in general rather than using beforesuite

is there a way to tell behat to load all php file from the bootstrap folder? how to load a file with the yaml?

iam using behat 3.15.0 

Best regards

**Comment by acoulton** [comment]
@BlackScorp I think there's a bit of confusion here (understandably). For historic reasons, the default path for the `FeatureContext` class and (any `Context` classes) is `%paths.base%/features/bootstrap`.

However this directory does not contain / is not used as "bootstrap" files in the sense we might think of them. It's just the base directory for Behat's custom PSR-0 autoloader - it's only used so that if e.g. your suite tries to load `FeatureContext` and no other autoloader can find that, the Behat autoloader will look in `%paths.base%/features/bootstrap/FeatureContext.php`.

When the docs talk about customising the bootstrap, they just mean that you can specify a different base directory for the custom autoloader. You've done that correctly with the `autoload` block in your YAML, but the `suites.default.paths.bootstrap` and `suites.default.bootstrap` keys you're defining aren't read or used by Behat AFAICS.

At the moment it's not possible to specify an actual bootstrap file(s) to execute before the suite although I agree this would be a very useful thing to have. We actually have an undocumented version of it as a custom extension in my company's behat-support package, but I think it'd be quite easy to port that over as an official feature. I'll try and take a look.

In the meantime if a `@BeforeSuite` hook is loading the bootstrap early enough for you then I would suggest creating a `BootstrappingContext`, registering it as your first context, and giving it a `@BeforeSuite` hook to require your bootstrap file.

**Comment by BlackScorp** [comment]
hi @acoulton thanks for the response. the BeforeSuite works just fine, but all my context classes have to extend it and also if i have a special before suite, i have to make sure that i call the parents ones as well.

Also if i move the BaseContext file to a different place, i have to adjust the path to include.

i gues i have to leave it then. because even if you add this new feature, i have to use an old version because of php 7.4 in legacy projects :(

**Comment by acoulton** [comment]
@BlackScorp that's a pity that you're blocked from upgrading from PHP 7.4.

However I think the workaround with using a context should work even on older Behat versions (we did that a lot before we started making extensions). I would create a dedicated context like:

```php
namespace Mollie\Behat;

use namespace Behat\Behat\Context\Context;

class BootstrappingContext implements Context
{
    /**
     * @BeforeSuite
     */
    public static function bootstrap()
    {
        require_once($PATH_TO_BOOTSTRAP); // or just inline your bootstrapping here, depending what you need
    }
}
```

And then in your YAML:

```yaml
default:
  suites:
    default:
      paths:
        features: '%paths.base%/../tests/Behat/features'
      contexts:
        # note this assumes composer can autoload these classes for you, if not you would need to customise
        # the behat autoloader configuration.
        - Mollie\Behat\BootstrappingContext
        - Mollie\Behat\FeatureContext
        - Mollie\Behat\ShopwareContext
```

So long as your `BootstrappingContext` is the first in the list, Behat will load it first, will find the BeforeScenario hook, and will run that hook before any BeforeScenario hooks that you have in any other contexts. You shouldn't need the BootstrappingContext to extend (or be a child of) any of your other contexts.

Your other option would be to borrow our custom BootstrappingExtension. You won't be able to use that package on PHP 7.4 either, but you only actually need [this class](https://github.com/ingenerator/behat-support/blob/1.x/src/Extension/BootstrappingExtension.php) and then a config like:

```yaml
default:
  suites:
    default:
      paths:
        features: '%paths.base%/../tests/Behat/features'
      extensions:
          # Or whatever you want to name the extension class
          # It just needs to be something composer can autoload
          Ingenerator\BehatSupport\Extension\BootstrappingExtension: ~
          # By default, will load '%paths.base%/test/bootstrap-behat.php'
          # Or customise it like:
          #    bootstrap_path: '%paths.base%/your/file.php' 
      contexts:
        - Mollie\Behat\FeatureContext
        - Mollie\Behat\ShopwareContext
```

Hope that helps?
