### ISSUE TITLE
Support PHP config for "tester" options

### ISSUE THREAD

**Issue by acoulton** [Behat/Behat#1624]
We haven't yet exposed an explicit PHP interface for configuring the `strict` or `stop-on-failure` runtime behaviour. I started looking at this and realised there's a couple of others:

```yaml
default:
  testers:
    # "Sets the strict mode for result interpretation" (which basically means fail on pending or undefined)
    strict: true
    stop_on_failure: true
    # "Tells tester to skip all tests" - tbh I'm not certain why you'd want this, and it doesn't appear to have feature coverage. 
    # Maybe for a profile that always runs equivalent to `--dry-run`?
    skip: true
  calls:
     # This is in a separate section of the configuration, but feels like it might be logically related to configuring
     # how the testers behave e.g. whether they pass or fail depending on particular conditions.
     # Note this is the only supported config key under `calls` at the moment, we might in future want to
     # add separate settings for collecting / handling deprecations which need to be configured alongside
     # error_reporting but don't really feel like they belong under something called `calls`.
    error_reporting: 32757
```

Arguably these are all behaviours of Behat for a specific `Profile` so they could be direct setters on the `Profile` config object. However that class is already getting quite heavy, and we probably don't want to add a lot more methods to that.

I think we should probably group these together into a new config object, either using `withXXX(true|false)` for each option:

```php
<?php
use Behat\Config\Config;
use Behat\Config\Profile;
use Behat\Config\TesterOptions;

return (new Config())
    ->withProfile((new Profile('default'))
        ->withTesterOptions((new TesterOptions)
            ->withStrictTesters(true)
            ->withStopOnFailure(false)
            ->withSkipAllTests(true)
            ->withErrorReporting(32757)
        )
    );
```

Or possibly with named methods for the on/off boolean states - I find these a little clearer to read, but they are obviously then harder if you wanted to set them based on some variable:

```php
<?php
use Behat\Config\Config;
use Behat\Config\Profile;
use Behat\Config\TesterOptions;

return (new Config())
    ->withProfile((new Profile('default'))
        ->withTesterOptions((new TesterOptions)
            ->failOnPendingOrUndefined() # or passOnPendingOrUndefined()
            ->stopOnFailure() # or continueOnFailure()
            ->skipAllTests() # I'm not convinced this one needs a negation
            ->withErrorReporting(32757)
        )
    );
```

I'm not sure how best to name this group of settings. 

`->withTesterOptions(new TesterOptions` roughly follows the underlying `testers` config key and the `Behat\Testwork\Tester\ServiceContainer\TesterExtension` that uses them. But I'm not sure if it's obvious to an outside user - `testers` on it's own might suggest the concept that `contexts` actually covers, but `TesterOptions` doesn't fit the pattern of the rest of our config.

These options are really to do with how Behat behaves when running tests. Apart from `skip`, they are sort of `ResultHandling` - `error_reporting` obviously runs code before the step executes and changes how the step behaves, but ultimately controls whether e.g. a PHP warning during a step causes the test to fail or not. So maybe `->withResultHandling((new ResultHandling)->stopOnFailure()` etc?

@carlos-granados WDYT?
