### ISSUE TITLE
The root config should have precedence over the imported one

### ISSUE THREAD

**Issue by stof** [Behat/Behat#230]
To avoid duplicating the `behat.yml.dist` file entirely to change only the base url for the MinkExtension, I tried to use the `imports` section to import the dist file from my `behat.yml`, modifying only the needed setting. But the result is not the expected behavior.

``` yaml
# behat.yml.dist
default:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: 'http://localhost/app_test.php/'
            default_session: symfony2
            javascript_session: selenium2
            selenium2:
                wd_host: http://127.0.0.1:4444/wd/hub
                browser: firefox
        Behat\Symfony2Extension\Extension:
            mink_driver: true
```

``` yaml
# behat.yml
imports:
    - behat.yml.dist

default:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: 'http://mysite.dev/app_test.php/'
```

I expected Behat to use `http://mysite.dev/app_test.php/` as base url after merging the configuration, but it is using `http://localhost/app_test.php/`
