### ISSUE TITLE
Truble with step in tests

### ISSUE THREAD

**Issue by spolischook** [Behat/Behat#270]
Given I am on homepage            # ...Bundle\Features\Context\FeatureContext::iAmOnHomepage()
      16384: MinLength is deprecated since version 2.1 and will be removed in 2.3. Use Length instead. in vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/MinLength.php line 31

My behat.yml:

``` yml
default:
  extensions:
    Behat\Symfony2Extension\Extension:
        mink_driver: true
    Behat\MinkExtension\Extension:
        default_session: 'symfony2'
        base_url: http://localhost/project/web
        browser_name: chrome
        selenium:
          host: 127.0.0.1
          port: 4444
        sahi:
            host: localhost
```

I use Symfony 2.2
