### ISSUE TITLE
Can't find context for...

### ISSUE THREAD

**Issue by kirkbushell** [Behat/Behat#285]
Can't find applicable feature loader for: "tests/features/pagination.feature"
Maybe you've forgot to create `features/` folder? 

This is supremely annoying. I can run features just fine, just not individual ones. Behat seems to completely ignore the config file, even if I pass it in:

bin/behat -c ./behat.yml tests/features/pagination.feature

Here is my yml file:

```
# behat.yml
default:
  paths:
    features: '%behat.paths.base%/tests/features'
    bootstrap: '%behat.paths.base%/tests/contexts'
  context:
    class: FeatureContext
  extensions:
    Behat\MinkExtension\Extension:
      default_session: selenium2
      javascript_session: selenium2
      base_url: http://localhost:5555
      selenium2: ~
```

I would love if someone can point out what I'm doing wrong, cos this is driving me batty.
