### ISSUE TITLE
Add context class resolvers

### ISSUE THREAD

**Issue by everzet** [Behat/Behat#420]
Thanks to #419 now you can specify constructor arguments for context classes, things can go quite mental (especially in case of some frameworks):

``` yml
  default:
    contexts:
      YourApp\CustomerBundle\Features\Context\CustomerContext:
        @app:customer.repository
```

We need to introduce context class resolver dependency on both `ContextEnvironmentHandler` AND `ArgumentHolder`, so we can do things like:

``` yml
  default:
    contexts:
      @CustomerBundle\CustomerContext:
        @app:customer.repository
```
