### ISSUE TITLE
Suite dependencies

### ISSUE THREAD

**Issue by robocoder** [Behat/Behat#436]
In order to fail fast
As a tester
I want to declare a critical path.

In Behat 3.x, it could mean: if a suite fails, then dependent suites would be skipped.

```
default:
  suites:
    authentication:
        paths: [ ... ]
        contexts: [ SignUpContext, LoginContext ]
    account:
        paths: [ ... ]
        contexts: [ AccountContext ]
        depends_on: authentication
```
