### ISSUE TITLE
Behat.yml is not validated completely before parsing

### ISSUE THREAD

**Issue by ciaranmcnulty** [Behat/Behat#473]
As a new user, I tried a paths key without array notation because I only had 1 path for my suite:

``` yml
suites:
  mysuite:
     paths: %whatever%/features/foo/
     # … rest of config
```

When running Behat I get a php fatal and stack trace, because that node isn't iterable.

Behat should validate these nodes before parsing and show appropriate error messages
