### ISSUE TITLE
BehatContext and PageObjectContext wont open browser

### ISSUE THREAD

**Issue by rogcg** [Behat/Behat#474]
Basically I want something like a super context (called **LoginContext**) that will call multiple subcontexts.

It will login the user and check if the user is on the customer account.

So I call the **CustomerLogin** context that will login the user, and later I call **CustomerAccount** that checks the user is on the customer account page.

``` php
<?php

use Behat\Behat\Context\BehatContext;

class LoginContext extends BehatContext
{   
    public function __construct()
    {
        $this->useContext("customer_login", new CustomerLoginContext());
        $this->useContext("customer_account", new CustomerAccountContext());    
    }

    /**
     * @Given /^I am logged$/
     */
     public function iAmLogged()
    {
        $this->getSubContext("customer_login")->iAmOnCustomerLogin();
        $this->getSubContext("customer_login")->iLogin();

        $this->getSubContext("customer_account")->iShouldSeeMyOrders();
    }
}
```

And my subcontexts are **PageObjectContext** classes, like this:

``` php
<?php

use pages\CustomerLogin;
use SensioLabs\Behat\PageObjectExtension\Context\PageObjectContext;

class CustomerLoginContext extends PageObjectContext
{
    ...
}
```

and this subcontext class call a **Page** class:

``` php
<?php

namespace pages;

use SensioLabs\Behat\PageObjectExtension\PageObject\Page;
use Commons\Utils;

class CustomerLogin extends Page
{   
    ...
}
```

Despite the tests pass, I don't see the browser opening. My **behat.yml** file is fine:

``` yml
login:
  paths:
    bootstrap: app/context
  context:
    class:  'LoginContext'
  extensions:
    SensioLabs\Behat\PageObjectExtension\Extension:
      namespaces:
        page: pages
    Behat\MinkExtension\Extension:
      base_url:  '<base-url-hidden-because-i-cant-show>'
      javascript_session:  'selenium'
      browser_name: googlechrome
      goutte:              ~
      selenium:
```

The tests run on command line, and the test pass, but the browser wont open. I guess it's because it's not using Mink's session to access the browser's driver. 

So my questions is, how do I use Mink's drivers with **PageObjects**. I've read somewhere that I should use BehatBundle class, but it's obsolete so I tried using **Symphony2Extension**. Am I following the right path? If not, which way should I follow?

Thanks in advance.
