### ISSUE TITLE
Config not inherited when using custom profiles while using Behat + Mink

### ISSUE THREAD

**Issue by radekbenkel** [Behat/Behat#530]
Assume that you have behat.yml.dist:

``` yaml
default:
    context:
        class: AggregationContext

    extensions:
        Behat\MinkExtension\Extension:
            default_session: selenium2
            base_url: http://example.com
            selenium2:
                wd_host: http://my-selenium-hub-host:4444/wd/hub
                capabilities:
                    version: ANY

phantomjs:
    extensions:
        Behat\MinkExtension\Extension:
            browser_name: phantomjs
```

which is stored inside repository. Now you want to modify only `wd_host` in order to use your local Selenium instance, but keep rest of the params unchanged.

So you would create `behat.yml` like this: 

``` yaml
imports:
  - behat.yml.dist

default:
    extensions:
        Behat\MinkExtension\Extension:
            selenium2:
                wd_host: http://localhost:4444/wd/hub
```

One could expect, that while running `behat -p phantomjs` my `wd_host` will be set to overridden version, which is `http://localhost:4444/wd/hub`, instead it's `http://my-selenium-hub-host:4444/wd/hub`. 

Was it intended to work this way?

(one solution would be copying `behat.yml.dist` to `behat.yml` without imports, but then config is in two places)

Used versions:

```
behat/behat                  v2.5.3 Scenario-oriented BDD framework for PHP 5.3
behat/mink                   v1.5.0 Web acceptance testing framework for PHP 5.3
behat/mink-extension         v1.3.1 Mink extension for Behat
```
