### ISSUE TITLE
Behat\Symfony2Extension\Extension could not be located

### ISSUE THREAD

**Issue by ghost** [Behat/Behat#553]
Hi everybody, 

I'm trying to use Behat on my Symfony project. After many documentations and installations, i got an exception when i run  : 

> $ php bin/behat --init --suite=test_suite

The exception : 

>  [Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]  
>  `Behat\Symfony2Extension\Extension` extension file or class could not be located.

composer.json : 

```
   ...
 "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "behat/behat": "3.0.*@dev",
        "behat/symfony2-extension": "2.0.*@dev",
        "behat/mink": "1.6.*@dev",
        "behat/mink-extension": "2.0.*@dev",
        "guzzle/guzzle": "2.4.*",
        "behat/mink-selenium2-driver": "1.2.*@dev",
        "behat/mink-browserkit-driver": "1.2.*@dev",
        "behat/mink-zombie-driver": "1.2.*@dev"
    },
...
```

behat.yml

```
default:
  paths:
    features: features
    bootstrap: %behat.paths.features%/bootstrap
  extensions:
    Behat\Symfony2Extension\Extension: 
      mink_driver: true
    Behat\MinkExtension\Extension:
      default_session: 'symfony2'
      selenium2: ~
  suites:
    test_suite:
      type: symfony_bundle
      bundle: "MzUiBundle"
```

[And I change my autoload.php](http://extensions.behat.org/symfony2/).

Someone can help me?
