### ISSUE TITLE
Behat 3.0.8 - Autoload contexts in several (sub)folders, possible ?

### ISSUE THREAD

**Issue by RynnHeldeD** [Behat/Behat#557]
Hello world :)

I am struggling since a few days to migrate my application to Behat 3. 
I would like to use the new "several contexts by suite" feature to have a more flexible and reusable code. I would also like to organize my context classes into several folders for more readability as I will have many of them.
# In theory

Below is an example of behat.yml and folders structures I would like to do : 

```
# behat.yml

default:
    autoload:
            - %paths.base%/bootstrap
    suites:
        aWebSuite-dev:
            paths:
                - %paths.base%/features/someWebFeatures
            contexts:
                - aWebFeatureContext
                - EnvironmentContext:
                    - Dev
                - WebContext
                - UserContext

        aMobileSuite-dev:
            paths:
                - %paths.base%/features/someMobileFeatures
            contexts:
                - aMobileFeatureContext
                - EnvironmentContext:
                    - Dev
                - MobileContext
                - UserContext
```

And the folders structure:

```
behat/
|- bin/
|- bootstrap/
   |- features/
      |- aMobileFeatureContext.php
      |- anotherMobileFeatureContext.php
      |- aWebFeatureContext.php
   |- interfaces/
      |- WebContext.php
      |- MobileContext.php
   |- environments/
      |- EnvironmentContext.php
   |- Modules/
      |- UserContext.php
      |- anotherModuleContext.php
|- features/
   |- someWebFeatures/
      |- feature1.feature
      |- feature2.feature
   |- someMobileFeatures/
      |- feature1.feature
      |- feature2.feature
```
# In practice

Such folders structure in `bootstrap/` does not work because Behat is not able to find and load the context classes. I think I understood that it was because Behat 3 use PSR-0 autoloader to load the context classes from `bootstrap/` and the structure above does not comply to PSR-0.

So for now, I am using the following structure : 

```
behat/
|- bin/
|- bootstrap/
      |- aMobileFeatureContext.php
      |- anotherMobileFeatureContext.php
      |- aWebFeatureContext.php
      |- WebContext.php
      |- MobileContext.php
      |- EnvironmentContext.php
      |- UserContext.php
      |- anotherModuleContext.php
```

But every context files are mixing in the same folder. Is there still a way to achieve my first idea ?

Thanks a lot !
