### ISSUE TITLE
Weird i18n problem with multiple suites

### ISSUE THREAD

**Issue by wouterj** [Behat/Behat#559]
| Q | A |
| --- | --- |
| Version | 3.0.8 |
## Setup

I've 2 suites:

``` yaml
default:
    suites:
        backend:
            paths: ["%paths.base%/features/backend"]
            contexts: [BackendContext, Behat\MinkExtension\Context\MinkContext]
        frontend:
            paths: ["%paths.base%/features/frontend"]
            contexts: [FrontendContext, Behat\MinkExtension\Context\MinkContext]
    extensions:
        Behat\MinkExtension:
            goutte: ~
            selenium2: ~
```

Both suites have one feature file which starts with:

``` cumcumber
# language: nl
...
```
## Problem

When I run `bin/behat`, only the steps of the first suite are translated, the second suite isn't run due to "missing step definition" errors for each step (because they are not translated).

I've tested both orders (first frontend, second backend and first backend, second frontend) and in both cases, the first is run, the second fails.

When I run them seperately using `bin/behat -s frontend` and `bin/behat -s backend`, they are executed without problems.
