### ISSUE TITLE
Profile configuration example (formatter)

### ISSUE THREAD

**Issue by tristanbes** [Behat/Behat#563]
Hi,

I can't find any example resources for the profil configuration. I'm hitting a wall for the formatter configuration.

I want to translate in v3 the following profiles (which were written for 2.x) under behat.yml but the `formatter` key isn't recognized

```
local:
    formatter:
        name: progress,html
        parameters:
            output_path: ,ci/build/behat/index.html
            language: en
    extensions:
        Behat\MinkExtension:
            selenium2:
                wd_host: http://172.16.1.1:4444/wd/hub

build:
    formatter:
        name: progress,junit,html
        parameters:
            output_path: ,ci/build/behat/junit,ci/build/behat/index.html
```

**Comment by murnieza** [comment]
I think it is already merged

**Comment by vpArth** [comment]
Configuration:
```yaml
default:
  formatters:
    progress: true
```
works for me.

One issue for me is Behat configuration is validated by `https://schemastore.azurewebsites.net/schemas/json/behat.json` schema.

I don't know there that validation is defined, but that schema has a typo: `"progress:" instead of "progress"`

It is may be some PhpStorm plugin...

Anybody knows who/where should/can to fix it?
