### ISSUE TITLE
 Context\FeatureContext context class not found and can not be used

### ISSUE THREAD

**Issue by tristanbes** [Behat/Behat#564]
It seems that there is a little auto loading problem in my configuration.

```
default:
    autoload: %paths.base%/features/Context
    ...
    suites:
        default:
            contexts:
                - Context\FeatureContext
                - behatch:browser
                - behatch:debug
```

```
 [Behat\Behat\Context\Exception\ContextNotFoundException]               
  Context\FeatureContext context class not found and can not be used.
```

My `FeatureContext` is located under `apps/features/Context/FeatureContext.php`

In my `composer.json`, the autolading is :

```
    "autoload": {
        "psr-0": {
            "": "src/",
            "Context": "apps/features/"
        }
    },
```

The namespace of the `FeatureContext.php` is : 

```
namespace Context;

class FeatureContext extends MinkContext implements KernelAwareContext
```

What did i missed please ?
