### ISSUE TITLE
Imports external config questions

### ISSUE THREAD

**Issue by xtrasmal** [Behat/Behat#567]
Hi there,

I have 3 files. One in the root folder, then custom config files in the 
modules test folder. 

``` yml


    # behat.yml
    imports:
    - /app/modules/Accounts/tests/behat.yml
    - /app/modules/Tickets/tests/behat.yml

    # app/modules/Accounts/tests/behat.yml
    accounts:
        filters:
            tags: "@accounts"
        paths:
            features: app/modules/Accounts/tests/features
            bootstrap: app/modules/Accounts/tests/features/bootstrap

    # app/modules/Tickets/tests/behat.yml  
    tickets:
        filters:
            tags: "@tickets"
        paths:
            features: app/modules/Tickets/tests/features
            bootstrap: app/modules/Tickets/tests/features/bootstrap 


```

When I run...

```
> behat --init -p accounts
```

or

```
> behat --init -p tickets
```

...the features and bootstrap folders are being created. 
But when I add a *.features, and run... 

```
> behat
```

... I get 0 Scenario's found.

How can I get this to work.
