### ISSUE TITLE
[RFC] Passing arguments to contexts via console

### ISSUE THREAD

**Issue by RynnHeldeD** [Behat/Behat#575]
Hello world :)

After discussing with @Yaboomaster about some difficulties I got during my migration from Behat 2 to 3, I got an idea of feature I think it hasn't been proposed yet.

Actually, it is possible to pass arguments to context though Behat.yml : 

```
default:
    suites:
        default:
            contexts:
                - MyAwesomeContext:
                    - /data/output
                    - http://localhost:8080
```

or

```
default:
    suites:
        default:
            contexts:
                - MyAwesomeContext:
                    outputFolder: /data/output
                    baseUrl: http://localhost:8080
```

Would it be possible to pass these arguments via the console too ? It could be something like this : 

```
bin/behat --suite=mySuite --MyAwesomeContext="/data/output","http://localhost:8080"
```

What do you think ?
