### ISSUE TITLE
YAML Spec Issues with imports

### ISSUE THREAD

**Issue by ragingdave** [Behat/Behat#592]
I am trying to import a yml file that is using an alias from the file is being imported into.

```
#behat.yml
#shortened for easy example
- FeatureContext:
    parameters:
        user: &USER
            username: default
            password: pass
imports:
    - 'something.yml'
```

```
#something.yml
#again shortened
- FeatureContext:
    parameters:
        user:
            <<: *USER
           password: diff_pass
```

This ends up failing because during import each individual file is loaded then merged, causing the reference to be undefined.  I would propose that all import files get concatenated and then loaded, this way the YAML spec (at least this part) will be supported and usable.
