### ISSUE TITLE
Splitting context classes in different Suites

### ISSUE THREAD

**Issue by BlackScorp** [Behat/Behat#603]
hello guys there is an problem with Context classes but maybe an missuse by me, i had following behat.yml files

```
default:
    autoload:
        '': %paths.base%/tests/Behat
    suites:
        silex:
            contexts:
                - Silex/Context
                - Silex/AccountContext
                - Silex/CityContext
        domain:
            contexts:
                - Domain/Context
                - Domain/AccountContext
                - Domain/CityContext
```

the idea was that i create classes with same names in different folders depends on suite, while the folders and filenames were created, the classnames are broken, the result is

``` php
/**
 * Behat context class.
 */
class Domain/AccountContext implements SnippetAcceptingContext
```

iam not sure, maybe i can setup the base directory of a suite for the classes with some other parameters?
