### ISSUE TITLE
Composer dont use the new directry structure for symfony

### ISSUE THREAD

**Issue by rkmax** [Behat/Behat#606]
I have a new project i'm using the new directory structure.

for example i have the cache dir on `var/cache` but behat creates her cache dir inside `app/cache`

``` yaml
"extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        ...
}
```
