### ISSUE TITLE
Supports a multiple --profile(s)

### ISSUE THREAD

**Issue by sorbing** [Behat/Behat#629]
What do you think about the possibility to specify multiple profiles when running the test? As example I have the several profiles in behat.yml:

``` yml
dev:
    mink:
        base_url: http://dev.mysite.com/
prod:
    mink:
        base_url: http://prod.mysite.com/
chrome:
    mink:
        browser_name: chrome
firefox:
    mink:
        browser_name: firefox
gprs:
    mink:
        sessions:
            selenium2:
                selenium2:
                    capabilities:
                        proxy: ~ # Proxy settings with 64kbps bandwidth
```

It would be convenient to apply the more profiles when running the tests:

``` bash
behat --profile=prod,firefox,gprs
```

What do you say?
