### ISSUE TITLE
[feature request] [behat.yml] default settings on profiles

### ISSUE THREAD

**Issue by MLoureiro** [Behat/Behat#632]
Hi guys

I was just updating my profiles to reflect Behat 3 changes
And noticed (or at least I couldn't make it work) that the default suite won't *share* definitions with the other suites, just like:

```
myProfile:
    suites:
        default:
            paths:
                - my/generic/first/feature/path/
                - my/generic/second/feature/path/
            context:
                - Namespace\Of\My\Generic\Context:
                    - param1: value1
                    - param2: value2
                    - param3: value3
        differentSuite:
            context:
                - Namespace\Of\My\Generic\Context:
                    param2: value2.2
        secondDifferent:
            filters:
                tags: @someTag
        # ...
```

In our case, we have several setup wizard possibilities, so we just copy paste and just change the filters.
And the possibility to change a single value and "inherit" the others would also be great.

What you guys think?
