### ISSUE TITLE
Profile and Suite Level filters

### ISSUE THREAD

**Issue by ragingdave** [Behat/Behat#636]
Although this has been touched on in a few other issues, I feel like there really should be more explanation.

for instance if I have:

profile level filter:

    tags: '~@app&&~@one-offs'

suite level filter for a special suite that needs to run the tags:

tags: '@app&&@direct'

I can't seem to get the @app tags features to run. It was my understanding that setting a profile level filter and then overriding it with a suite level filter, will allow it to run.

In this way is there actually no correlation between profile and suite level filters, or are they actually overridden by one or the other?  It seems a bit confusing on where there is inheritance of settings and where there isn't.

**Comment by everzet** [comment]
Yes you should be able to:

```
default:
  gherkin:
    filters:
      tags: wip
  suites:
    mine:
      filters:
        tags: mine
```
