### ISSUE TITLE
Merging configurations

### ISSUE THREAD

**Issue by ice9js** [Behat/Behat#646]
Hi, 

I've had some trouble regarding the way configuration files are merged right now. So here are some idea's from me. 

Imports

I think that the imported configuration should not overwrite the variables stored in the current config file.
Basically, if you are importing a configuration, you're importing some variables that are the same for multiple projects and you want to narrow them down a bit.

Arrays

When using arrays as parameters, would it be a big issue to merge them instead of completely replacing them ?

Example: 

behat.yml 
```
default:
    suites:
        desktop:
            settings:
                arr1:
                    var1: foo
                    var2: bar
                arr2:
                    var3: something

environment1:
    suites:
        desktop:
            settings:
                arr1:
                    var4: somevar
```

config.xx.yml
```
imports:
    - behat.yml
default:
    suites:
        desktop:
            settings:
                arr1:
                    var2: changed
                arr2:
                    var5: new
```

Then, running behat with:
```
bin/behat -c config.xx.yml -p environment1
```

Should have these settings:
```
settings:
    arr1:
        var1: foo
        var2: changed
        var4: somevar
     arr2:
        var3: something
        var5: new
```

Right now it'd look like this:
```
settings:
    arr1:
        var4: somevar
     arr2:
        var3: something
```

What's your opinion on this ?

**Comment by jhedstrom** [comment]
I'm seeing this as well. Changed values from imports don't override values that are already defined it seems.

**Comment by stof** [comment]
Are you using Behat 2.5 or 3.0 ?

**Comment by jhedstrom** [comment]
I'm seeing this on Behat 3. I recall this working as expected on 2.5.

**Comment by stof** [comment]
Well, Behat 2.5 did not have any concept of suites, so there were no suite settings. And suite settings are indeed not merged deeply

**Comment by jhedstrom** [comment]
I'm seeing this trying to override an extension setting, so suites shouldn't impact it:

```yaml
default:
  suites:
    default:
      contexts:
        - ...
  extensions:
    Behat\MinkExtension:
      base_url: http://default.url
imports:
  - behat.local.yml
```

and then importing another file, trying to set `base_url` to something else doesn't override the value set in `behat.yml`.
