### ISSUE TITLE
Behat 3: `FeatureContext` context class not found and can not be used. 

### ISSUE THREAD

**Issue by bentcoder** [Behat/Behat#648]
Although there are many examples for same reason, I guess this is to do with autoload but so far I couldn't find a solution to pass variables to constructor via behat.yml which I was able to do when I was using Behat v2. Can anyone tell me what I'm doing wrong because I'm getting error below:

```
 [Behat\Behat\Context\Exception\ContextNotFoundException]       
  `FeatureContext` context class not found and can not be used. 
```

Used this command to set it up: `php bin/behat --init --suite=test_suite`

**_behat-three/behat.yml**_

``` yaml
default:
    autoload:
        - %paths.base%/features/bootstrap/
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://behat-three.local/app_dev.php
            browser_name: firefox
            sessions:
                symfony2:
                    symfony2: ~
    suites:
        test_suite:
            type: symfony_bundle
            bundle: SiteMainBundle
            mink_session: symfony2
            contexts:
                - FeatureContext:
                    output_path: '/build/behat/output/'
```

**_behat-three/features/bootstrap/Site/MainBundle/Features/Context/FeatureContext.php**_

``` php
<?php

namespace Site\MainBundle\Features\Context;

use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\MinkExtension\Context\MinkContext;

class FeatureContext extends MinkContext implements Context, SnippetAcceptingContext
{
    public function __construct($output_path)
    {
    }
}

```

**_behat-three/composer.json**_

``` json
{
    "name": "symfony/framework-standard-edition",
    "autoload": {
        "psr-0": { "": "src/", "SymfonyStandard": "app/" }
    },
    "require": {
        "php": ">=5.4",
        "symfony/symfony": "2.5.*",
        "behat/behat": "3.0.14",
        "behat/behat-bundle": "1.0.0",
        "behat/symfony2-extension": "2.0.0",
        "behat/mink": "1.6.0",
        "behat/mink-extension": "2.0.1",
        "behat/mink-browserkit-driver": "1.2.0",
        "behat/mink-goutte-driver": "1.1.0",
        "behat/mink-selenium2-driver": "1.2.0"
    },
```

**_Directory structure**_

```
behat-three
    features
        bootstrap
            Site
                MainBundle
                    Features
                        Context
                            FeatureContext.php
```
