### ISSUE TITLE
behat --init generate FeatureContext class implementing none existing interfaces

### ISSUE THREAD

**Issue by gondo** [Behat/Behat#665]
im using behat v3.0.14 together with Symfony2 application
my `composer.json` looks like this:

```
    "behat/symfony2-extension": "~2.0",
    "behat/mink-extension": "@stable",
    "behat/mink-browserkit-driver" : "@stable",
    "behat/mink-goutte-driver": "@stable",
    "behat/mink-selenium2-driver": "@stable"
```

and my `behat.yml` like this:

```
default:
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            sessions:
                my_session:
                    symfony2: ~
    suites:
        my_suite:
            type: symfony_bundle
            bundle: MyTestBundle
```

when i call `bin/behat --init` than `FeatureContext.php` file is generated and it looks like this:

```
<?php

namespace My\TestBundle\Features\Context;

use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class FeatureContext implements Context, SnippetAcceptingContext
{
    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct()
    {
    }
}
```
## The Problem

Interfaces `Behat\Behat\Context\Context` and `Behat\Behat\Context\SnippetAcceptingContext` does not exist.
However there is existing interfaces `Behat\Behat\Context\ContextInterface`.
This is disturbing as my IDE (PhpStorm) complains about incorrect code.
