### ISSUE TITLE
Injecting environment variables into behat.yml

### ISSUE THREAD

**Issue by JANorman** [Behat/Behat#697]
Hi,

Thanks for providing such a great library. 

I've looked around, but have been unable to find any way to inject environment variables into the behat.yml file (without modifying the file at runtime). 

We use Mink, and specifically want to pull the "wd_host" parameter from the environment variable using behat parameters. Is it possible to do this?

Here is what I would ideally like:

```
default:
    paths:
        features: features
        bootstrap: %behat.paths.features%/bootstrap
    extensions:
        Behat\MinkExtension\Extension:
            goutte: ~
            selenium2:
                browser: "chrome"
                wd_host: *%selenium_url%*
```

**Comment by nchagrass** [comment]
Why not using a different profile that will extends the default one ?

```yaml
default:
    paths:
        features: features
        bootstrap: %behat.paths.features%/bootstrap
    extensions:
        Behat\MinkExtension\Extension:
            goutte: ~
            selenium2:
                browser: "chrome"
                wd_host: "whateverUrl"

production:
    extensions:
        Behat\MinkExtension\Extension:
            selenium2:
                wd_host: "anotherUrl"
```
