### ISSUE TITLE
It is apparently impossible to use multiple contexts in a suite if using Symfony2Extension

### ISSUE THREAD

**Issue by Tocacar** [Behat/Behat#701]
I have tried every config combination humanly possible, but cannot get two contexts to run.  As soon as I add a 'contexts:' key to my config, even the FeatureContext class is no longer recognised.

This is my behat.yml file:

```
default:
    suites:
      my_suite:
        type: symfony_bundle
        bundle: MyCoolBundle
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://ams.ldev
            selenium2: ~
            symfony2: ~
            sessions:
                default:
                    symfony2: ~
```

And I have the default directory structure created by the behat init command.  How can I change the above config to allow me to have two context classes for the suite?

Ideally I'd like to define a 'global' context class that contains database-related code that should run on each execution of my tests. But if I can even just get this working inside one suite that'd do me for now.

Thanks for any help.
