### ISSUE TITLE
Behat 3.0 and mink selenium extension with multiple host

### ISSUE THREAD

**Issue by jbouzekri** [Behat/Behat#715]
Hi,

I have an application (type SAS) where my users switch from a domain to another.

I wanted to create a test suite on one domain and another one on a second however I cannot seem to make behat switch from one base url to the other.

Is there anyone who could help me please ?

This is my behat.yml. With this configuration, I would like to run all scenario with the tag club2 on club2.localhost and the other on club1.localhost. With this configuration, I can make the club2 suite work by runing the command : behat --suite=club2 --profile=club2. But I am looking for a way to run all suite in one command and automaticaly switching profile in the suite.

``` yml
default:
    autoload:
        '': %paths.base%/features/bootstrap
    extensions:
        Behat\Symfony2Extension: ~
        SensioLabs\Behat\PageObjectExtension: ~
        Behat\MinkExtension:
            base_url: http://club1.localhost/
            selenium2: ~
    suites:
        default:
            contexts:
                - Context\FeatureContext
                - Context\SecurityContext
            filters:
                tags: ~@club2
        club2:
            contexts:
                - Context\FeatureContext
                - Context\SecurityContext
            filters:
                tags: @club2

club2:
    extensions:
        Behat\Symfony2Extension: ~
        SensioLabs\Behat\PageObjectExtension: ~
        Behat\MinkExtension:
            base_url: http://club2.localhost/
            selenium2: ~
```

Thanks in advance

**Comment by jbouzekri** [comment]
I don't know if I went the right way, but I found a solution by creating a custom context which modify all context in the environment before each scenario.

``` php
<?php

namespace Context;

use Behat\Behat\Hook\Scope\BeforeScenarioScope;

/**
 * Description of MinkOverrideContext
 *
 * @author jobou
 */
class MinkOverrideContext extends Base\BaseMinkContext
{

    protected $baseUrl;

    public function __construct($base_url)
    {
        $this->baseUrl = $base_url;

    }

    /** @BeforeScenario */
    public function gatherContexts(BeforeScenarioScope $scope)
    {
        $environment = $scope->getEnvironment();

        foreach ($environment->getContexts() as $context) {
            if ($context instanceof \Behat\MinkExtension\Context\RawMinkContext) {
                $context->setMinkParameter('base_url', $this->baseUrl);
            }
        }
    }
}

```

And then loading it only for my club2 suite : 

``` yml
    suites:
        club2:
            contexts:
                - Context\FeatureContext
                - Context\SecurityContext
                - Context\MinkOverrideContext:
                    base_url: http://club2.clubor.localhost/
            filters:
                tags: @club2
```

It seems to work but I would like to have your feedback on good and bad practice of what I am doing. Thanks in advance
