### ISSUE TITLE
Adding support for responsive feature testing

### ISSUE THREAD

**Issue by gries** [Behat/Behat#718]
Hi,

our current setup includes behat + mink + browser-stack. 
What we want to achieve is to test big list of features on a responsive-design on multiple browsers/devices, with the ability to to enable/disable features based on the browser-size.

This currently requires us todo the following:

* Add a mink session + suite for every device / browser configuration.

```yaml
suites:
    ios_7_iphone5:
      paths:  [ %paths.base%/features ]
      contexts: [ FeatureContext ]
      mink_session: ios_7_iphone5
      filters:
        tags: @iphone5c

extensions:

    MinkExtension:
      base_url: http://my-site.dev
      sessions:
        ios_7_iphone5:
          browser_stack:
            device: "iPhone 5S"
            ...
```
* Add a tag for every browser-configuration that should have this feature enabled.
```gherkin
@iphone5c
@iphone5s
@iphone6
@iphone6plus
Feature: Entity Status
  In order to know the current state of my entity
  As a User
  ....
```
As you can image this gets really messy really quick.
Adding a mink-session + suite for every browser-config is not that big of a deal,
But always keeping track of the exact browser-configurations for every feature that supports this configuration is not possible if you have a decent amount of browser-configurations.

I tried to come up with a little hack using a ```beforeScenario``` hook that gets the current driver checks the window-size and compares it to a feature-tag ```@min-window-width:700px```

This works just fine the only problem is that I don't have the possibility to skip the scenario / feature at this point.

Please give me some feedback if my approach is even viable or if this kind of usecase can be achieved in another way.

**Comment by gries** [comment]
I case someone is interested I create a behat-extension that does that: https://github.com/2bepublished/BehatResponsiveFeaturesExtension any feedback is still welcome.

**Comment by timiTao** [comment]
@gries  I think you problem is not functionality, but management over tests.

In my opinion, Context should be iPhone5(5c|5s|6|6plus) but suite should be package  additionality of your page. In this case, the tags are unneserry like iphone5s. For given context, you should tests given feature. This way you will have for N configuration, but at scenarios, you will have clear view of behavioral. In this case, you don't need validation to check if run scenario - you simply control everything in configuration files ( you could have more)

**Comment by gries** [comment]
Hi,
how would that work? I could make a Context for all devices / configurations but that wouldn't help me in not executing features for those devices.

Maybe I didn't get your answer right, but if I lets say configure multiple contexts for one suite let's call the suites `core` and `cart` I'd have a configuration like this.

```yaml
default:
    suites:
        core:
            contexts:
                - FirefoxContext
                - iPhoneContext
            paths: 
                - features/core 
        cart:
            contexts:
                - FirefoxContext
                - iPhoneContext
            paths: 
                - features/cart
```

And my feature-files look something like this:
```
features/
    core/
        hello-world.feature ; executed on all browsers
    cart/
        navigation.feature ; executed on all browsers
        item_count.feature ; executed on all browsers with with a screen > 500
```

How could I now configure contexts to achieve my goal?
