### ISSUE TITLE
Default suite's contexts not loaded

### ISSUE THREAD

**Issue by legovaer** [Behat/Behat#741]
Hi,

On the project I'm working on, we're using lots of custom contexts. A lot of these contexts should be used in every suite (so by default, it should get loaded).

If I add these contexts to the default suite and try to run one of my non-default suites, Behat tells me that the Context is not found.

This is the yaml file I'm using;
```
default:

  suites:
    default:
      contexts:
        - Foo\Context\FooContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Bar\Context\BarContext
       ... 8 other contexts
      paths:
        - %paths.base%/../features
    
    project_x:
      contexts:
        - Bar\Context\BarContext
      paths:
        - %paths.base%/../features/bar
```
When I try to run Behat using `./bin/behat --suite=project_x`, I get the following error;

`Drupal\DrupalExtension\Context\MinkContext` context is not found in the suite environment. Have you registered it?`

After adding that Context to the contexts of `project_x`, the test runs without any issues. Is this the default behavior? Do I have to add every context I might use to every suite?
