### ISSUE TITLE
How to use the config key `argument`?

### ISSUE THREAD

**Issue by Sorbing** [Behat/Behat#761]
Tell me please, how to use the config key `argument`?

**Comment by stof** [comment]
Which config key are you talking about ?

**Comment by Sorbing** [comment]
I mean the config key `testwork.argument` (I found it in the reference: `behat --config-reference`)
```
testwork:
  argument: []
  autoload:
    ...
```
