### ISSUE TITLE
Allow different browser/setup in suites

### ISSUE THREAD

**Issue by sourcerer-mike** [Behat/Behat#767]
It would be nice if different Browsers / Extensions could be used per suite:

```
default:
  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig
      file_name: index
    Behat\MinkExtension:
      sessions:
        default:
          goutte: ~
  autoload:
    '': %paths.base%/tests/features/bootstrap
  suites:
    ie8:
      paths: [ %paths.base%/tests/features ]
      contexts:
        - Behat\MinkExtension\Context\MinkContext
        - SeleniumContext
        - WordPressContext
    iPhone5:
      extensions:
        Behat\MinkExtension:
          sessions:
            default:
              goutte: ~
            iPhone5:
              browser_stack:
                capabilities:
                  browserName: iPhone
                  platform: MAC
                  device: iPhone 5
```
