### ISSUE TITLE
Behat 3 yaml: disable colors/ansi

### ISSUE THREAD

**Issue by OutOfBrain** [Behat/Behat#788]
I am creating a pretty output on my jenkins build setup, but I want to remove the colors. I know that it is possible to do this as cli option, but we don't want to customize the cli calls on all system, instead configure that in behat.yml.

Anyone who can help?

```javascript
default:
    formatters:
        progress: true
        pretty:
            output_path: %paths.base%/build/behat/summary.html
        junit:
            output_path: %paths.base%/build/behat
```

**Comment by everzet** [comment]
```
default:
    formatters:
        progress: true
        pretty:
            output_path: %paths.base%/build/behat/summary.html
            output_decorate: false
        junit:
            output_path: %paths.base%/build/behat
```
