### ISSUE TITLE
Global cache dir config

### ISSUE THREAD

**Issue by Soullivaneuh** [Behat/Behat#800]
On my behat config, I have two extension with a cache dir options:

```yaml
default:
    gherkin:
        cache: app/cache/test/behat/behat_gherkin_cache
    testers:
        rerun_cache: app/cache/test/behat/behat_rerun_cache
    calls:
        error_reporting: 14335 # E_ALL & ~E_USER_DEPRECATED
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            sessions:
                default:
                    symfony2: ~
```

It could be great to have a global cache_dir option and variable that extension could get instead of fallback to system tmp dir.

So we could have this king of configuration:

```yaml
default:
    cache_dir: app/cache/test
    calls:
        error_reporting: 14335 # E_ALL & ~E_USER_DEPRECATED
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            sessions:
                default:
                    symfony2: ~
```

Extension would append them directories path to the cache_dir option.

What do you think?
