### ISSUE TITLE
Running tests individually in behat3

### ISSUE THREAD

**Issue by BentCoder** [Behat/Behat#811]
Hi,

With behat2, we could run individual features with:
```
bin/behat --profile=api AdminAccessControl.feature
bin/behat --profile=api AdminAccessControl.feature:12
```
however, I cannot find a way of doing same in behat3. I tried:
```
bin/behat --suite=api AdminAccessControl.feature
No scenarios
No steps
0m0.03s (13.78Mb)
                                                                    
  [Behat\Testwork\Tester\Exception\WrongPathsException]             
  No specifications found at path(s) `AdminAccessControl.feature`.  
                                                                    
behat [-s|--suite="..."] [-f|--format="..."] [-o|--out="..."] [--format-settings="..."] [--init] [--lang="..."] [--name="..."] [--tags="..."] [--role="..."] [--story-syntax] [-d|--definitions="..."] [--append-snippets] [--no-snippets] [--strict] [--rerun] [--stop-on-failure] [--dry-run] [paths]
```

The only thing works is: `bin/behat --suite=api` but it runs all tests.

**behat.yml**
```
default:
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://webservice.local/app_test.php/
            sessions:
                symfony2:
                    symfony2: ~
    suites:
        api:
            type: symfony_bundle
            bundle: ApplicationApiBundle
            mink_session: symfony2
            contexts:
                - Application\ApiBundle\Features\Context\FeatureContext:
                    baseUrl: http://webservice.local/app_test.php/
```

**Folder structure**

```
src/Application/ApiBundle/Features/AdminAccessControl.feature
src/Application/ApiBundle/Features/Context/FeatureContext.php
```

Thanks

**Comment by stof** [comment]
Can you try ``bin/behat --suite=api src/Application/ApiBundle/Features/AdminAccessControl.feature`` ?

I don't remember how the path name look like when using the symfony_bundle type, as I don't use it myself.

**Comment by BentCoder** [comment]
Thanks, that worked and also the one below works as well.

```
bin/behat --suite=api @ApplicationApiBundle/AdminAccessControl.feature
bin/behat --suite=api @ApplicationApiBundle/AdminAccessControl.feature:12
```

**Comment by stof** [comment]
ah yeah, this was how I provided it in Behat 3.

**Comment by BentCoder** [comment]
Do you know how `formatter` works in 3? The code below work in version 2 but not in 3. I think there is a lack of documentation in particular to 3 in general.

```
#behat.yml
default:
    formatter:
        name: pretty
        parameters:
            output_styles:
                comment: [ magenta ]
```
