### ISSUE TITLE
Suite-specific parameters in BeforeSuite and AfterSuite hooks

### ISSUE THREAD

**Issue by christeredvartsen** [Behat/Behat#861]
In Behat-2 the `@BeforeSuite` and `@AfterSuite` hooks received an event object that had the `getContextParameters` method. In Behat-3 these methods now receive a scope object that does not seem to have a similar method.

Is there a way to do something similar in Behat-3? I have some different suites that all have suite-specific parameters that I would love to access in the before/after suite hooks. As those methods are static I can't access the parameters sent to the featurecontext constructor.

**Comment by stof** [comment]
Well, suite-specific parameters are stored in the Suite object in Behat 3, which is available in the SuiteScope.

**Comment by christeredvartsen** [comment]
Care to paste a short example on how to fetch them, and how they should be specified in the configuration file?

**Comment by stof** [comment]
anything inside ``suites`` in your config file (inside the name of the current suite) will be stored in suite attributes

**Comment by christeredvartsen** [comment]
Thanks, got it working now so feel free to close the issue. This should perhaps be written in the docs somewhere as well.

**Comment by christeredvartsen** [comment]
Is there a way to specify default params for all suites or do I have to repeat the configuration values for all suites?

```yml
default:
    suites:
        default:
            param: value
            contexts: [ FeatureContext ]
        someSuite:
            param: value
            contexts: [ FeatureContext ]
        otherSuite:
            param: value
            contexts: [ FeatureContext ]
otherProfile:
     suites:
        default:
            param: otherValue
        someSuite:
            param: otherValue
        otherSuite:
            param: otherValue
```

Say I want the `param` parameter to be set to `value` for all suites, but when running the `otherProfile` profile I'd like the value to be set to `otherValue` instead. Is the above snippet the way to handle this, or is there some other way to make suites inherit parameters from other suites?
