### ISSUE TITLE
Browser language

### ISSUE THREAD

**Issue by Nexyssify** [Behat/Behat#879]
Hello, 

I want to know how I can force the language of the browser ? 
Today i have this code in my behat.yml : 
`default:
    formatters:
        pretty:
            verbose:  true
            paths:    false
            snippets: false
    suites:

extensions:
        Behat\MinkExtension:
            sessions:
                default:
                    selenium2: ~
            browser_name: firefox
            show_auto:    false
            base_url: ...
        Behat\Symfony2Extension: ~

firefox:
     extensions:
         Behat\MinkExtension:
             sessions:
                 default:
                     selenium2: ~
             browser_name: firefox
             show_auto:    false
             base_url: ...
         Behat\Symfony2Extension: ~

chrome:
     extensions:
         Behat\MinkExtension:
             sessions:
                 default:
                     selenium2: ~
             browser_name: googlechrome
             show_auto:    false
             base_url: ...
         Behat\Symfony2Extension: ~

ie:
     extensions:
         Behat\MinkExtension:
             sessions:
                 default:
                     selenium2: ~
             browser_name: ie
             show_auto:    false
             base_url: ...
         Behat\Symfony2Extension: ~
`

Plus my test. 

Thank's.

**Comment by janipalsamaki** [comment]
This is one way of forcing the browser language in `behat.yml`. This works with Behat version 3. In this case, the language is set to Japanese:

```yml
default:
  suites:
    default:
      contexts:
        - FeatureContext:
  extensions:
    Behat\MinkExtension:
      goutte:
        guzzle_parameters:
          verify: false
          headers:
            Accept-Language: ja
      selenium2:
        browser: chrome
      base_url: http://www.example.com/
```
