### ISSUE TITLE
behat 3.1.0 imports

### ISSUE THREAD

**Issue by richardtape** [Behat/Behat#884]
Hi. First: Behat is amazing. Thank you, thank you, thank you, thank you.

Second, I'm trying to use `imports` in order to have a 'base' behat.yml file which then allows me to import a separate config file with parameters/credentials that I don't want to commit to a repo. I've tried so many different ways, and googled around, but can't quite get there. Here's a shortened example;

`behat.yml` file

```
default:
    extensions:
        Behat\MinkExtension:
            base_url: http://cmslocalhost.dev
            goutte: ~
            default_session: goutte
            javascript_session: selenium_firefox_session
            sessions:
                goutte_session:
                    goutte:
                        guzzle_parameters:
                            ssl.certificate_authority: false
                selenium_chrome_session:
                    selenium2:
                        browser: chrome
                selenium_firefox_session:
                    selenium2:
                        browser: firefox
        Sanpi\Behatch\Extension: ~
    suites:
        default:
            contexts:
                - FeatureContext
                - Behat\MinkExtension\Context\MinkContext
                - Behatch\Notifier\Slack

chrome:
    extensions:
        Behat\MinkExtension:
            default_session: selenium_chrome_session

firefox:
    extensions:
        Behat\MinkExtension:
            default_session: selenium_firefox_session

imports:
    - ./config.yml
```

`config.yml` file (in the root of the project, alongside behat.yml)

```
default:
    suites:
        default:
            contexts:
                - Behatch\Notifier\Slack:
                    url: https://hooks.slack.com/services/some/slack/webhook/url/here
```

However, when I run `./vendor/bin/behat` the Slack notifier isn't receiving any parameters which suggests the import hasn't worked. There are no warnings or errors from behat itself, but the Slack notifier throws some warnings with regards to missing arguments.

For clarity, here's my `composer.json`

```
{
    "name": "ubc/ubehatc",
    "authors": [
        {
            "name": "Richard Tape",
            "email": "richard.tape@ubc.ca"
        }
    ],
    "require": {
        "behat/mink-extension": "*",
	"behat/mink-goutte-driver": "*",
        "behat/mink-selenium2-driver": "^1.3",
        "phpunit/phpunit": "^5.3",
        "behatch/contexts": "^2.5",
        "behatch/notifiers": "^1.0",
        "maknz/slack": "^1.7"
    },
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    }
}

```
I've tried the imports at the top. I've tried an absolute path to the config.yml file. I've tried just `config.yml` (no `./`) No dice.

(Also note: if I put the config 'in-line' in the main behat.yml file as parameters, it works as expected)

I'm almost certainly doing something stupid... any ideas?

**Comment by janipalsamaki** [comment]
Same as #646?

**Comment by Skullywag** [comment]
Also trying to do this, if you move the whole section, in my case:
```
suites:
    default:
      contexts:
        - Ucas\Context\FeatureContext:
          - 'test'
          - 'test2'
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
```

into the imported config file it will work, imported config cannot overwrite the behat.yml config. Seems a bit wrong to have to copy the whole lot to the non git tracked file.
