### ISSUE TITLE
Question about test in api.feature

### ISSUE THREAD

**Issue by aronbeal** [Behat/Behat#886]
Hi,

I've been trying to pass the base tests in my [forked variant](https://github.com/aronbeal/drupalextension) of drupalextension to remove barriers to inclusion, but I'm not able to pass this one (in api.feature):

```gherkin
 @d7 @d8 @current
  Scenario: Node hooks are functioning
    Given "article" content:
    | title        | body        | published on       | status | promote |
    | Test article | PLACEHOLDER | 04/27/2013 11:11am |      1 |       1 |
    When I am on the homepage
    Then I should see the text "Sat, 04/27/2013 - 11:11"
```
Figuring I had munged up something important in my variant, I installed a fresh copy via the [docs](https://behat-drupal-extension.readthedocs.io/en/3.1/localinstall.html), and configured behat.yml to point to the features directory in drupalextension:

```yaml
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
      paths: 
        - '%paths.base%/vendor/drupal/drupal-extension/features'
  extensions:
#..and so on and so forth
```
Running the test here, I get the following (basing against a fresh d7 site install):
```
  Scenario: Node hooks are functioning                   # vendor/drupal/drupal-extension/features/api.feature:168
    Given "article" content:                             # Drupal\DrupalExtension\Context\DrupalContext::createNodes()
      | title        | body        | published on       | status | promote |
      | Test article | PLACEHOLDER | 04/27/2013 11:11am | 1      | 1       |
    When I am on the homepage                            # Drupal\DrupalExtension\Context\MinkContext::iAmOnHomepage()
    Then I should see the text "Sat, 04/27/2013 - 11:11" # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()
      The text "Sat, 04/27/2013 - 11:11" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)
```
I see green lights on your TravisCI builds, so obviously this is passing for you.  It's the 'published on' field that I'm wondering about.  Is this supposed to be 'changed'?  What is it testing? Is there something special in the TravisCI drupal builds that includes this field?
