### ISSUE TITLE
Correctly configuration for Behat, Selenium grid to take Screenshots

### ISSUE THREAD

**Issue by sVeloper** [Behat/Behat#908]
Hello, 
i´am new on Behat Framework and i try to use it with Selenium-Grid. 
That allows me to use several Browsers for testing. 
When i get a arror, one screenshot should be taken.
Problem: Configuration of Behat:
Project folder structure:
```
     BehatTest
         features
         screenshot
         vendor
         behat.yml
         composer.json
```

Composer.json:
```
{
  "require": {
    "behat/behat": "~3.0",
    "behat/mink": "1.6.*",
    "behat/mink-goutte-driver": "1.*",
    "behat/mink-extension": "2.*",
    "behat/mink-selenium2-driver": "1.*",
    "symfony/process": "^3.1",
    "behat/mink-browserkit-driver": "1.2.*",
    "behat/symfony2-extension": "^2.1"

  }
}
```
After "composer install" i get some suggestions, but i guess, that i dont need it.
At next i create behat.yml like this:

```
default:
    paths:
        features: features
        bootstrap: %behat.paths.features%/bootstrap
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://test/app_test.php
            browser_name: firefox
            sessions:
                goutte:
                    goutte: ~
                selenium2:
                    selenium2: ~
                symfony2:
                    symfony2: ~
    suites:
        backend:
            type: symfony_bundle
            bundle: ApplicationBackendBundle
            mink_session: selenium2
            contexts:
                - BehatTest\Features\Bootstrap\Context;:
                    screen_shot_path: BehatTest/screenshot
```

And my FeatureContext.php

```
<?php

namespace BehatTest\Features\Bootstrap\Context;

use Behat\Behat\Hook\Scope\AfterStepScope;
use Behat\Mink\Driver\Selenium2Driver;
use Behat\MinkExtension\Context\MinkContext;


/**
 * Features context.
 */
class FeatureContext extends MinkContext
{

}
```
But, when i retrieve behat version: vendor/bin/behat -v
I get this error:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
>   Unrecognized option "paths" under "testwork"

and big Exception trace:

Exception trace:
```
 () at /home/dev/ez/BehatTest/vendor/symfony/config/Definition/ArrayNode.php:317
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /home/dev/ez/BehatTest/vendor/symfony/config/Definition/BaseNode.php:264
 Symfony\Component\Config\Definition\BaseNode->normalize() at /home/dev/ez/BehatTest/vendor/symfony/config/Definition/Processor.php:33
 Symfony\Component\Config\Definition\Processor->process() at /home/dev/ez/BehatTest/vendor/behat/behat/src/Behat/Testwork/ServiceContainer/ContainerLoader.php:81
 Behat\Testwork\ServiceContainer\ContainerLoader->processConfig() at /home/dev/ez/BehatTest/vendor/behat/behat/src/Behat/Testwork/ServiceContainer/ContainerLoader.php:65
 Behat\Testwork\ServiceContainer\ContainerLoader->load() at /home/dev/ez/BehatTest/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:181
 Behat\Testwork\Cli\Application->createContainer() at /home/dev/ez/BehatTest/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:157
 Behat\Testwork\Cli\Application->createCommand() at /home/dev/ez/BehatTest/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:119
 Behat\Testwork\Cli\Application->doRun() at /home/dev/ez/BehatTest/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /home/dev/ez/BehatTest/vendor/behat/behat/bin/behat:32
```

How could i solve that?
Thx very much.
