### ISSUE TITLE
behat.yml for several nodes of Selenium2

### ISSUE THREAD

**Issue by sVeloper** [Behat/Behat#912]
Hello,

I can test with my behat-configuration localy.
At next i try to connect to several nodes on selenium grid. Each node has own configuration.
I use Behat3 and mink-selenium2-driver
My yml-file looks like this:

```
internetExplorer:
  extensions:
    Behat\Symfony2Extension: ~
    Behat\MinkExtension:
      base_url: http://localhost.com/myItems
      javascript_session: 'selenium2'
      selenium2:
          wd_host: http://hub.selenium.intern.com:4444/wd/hub
          browser: iexplore
          capabilities: {'platform':'XP', 'browser':'iexplore', 'version':'8'}
      goutte: ~
  suites:
    mink_session:
      contexts:
        - FeatureContext:
```
This example i found on: 
https://gist.github.com/MajorOutage/7055573ee0acc96b6d67/revisions

Sadly i get this exception:

>    Could not open connection: Error forwarding the new session cannot find : Capabilities [{browser=iexplore, name=Behat feature suite, browserName=iexplore, ignoreZoomSetting=false, version=8, platform=XP, tags=[debian-ez, PHP 5.6.19-0+deb8u1]}] (Behat\Mink\Exception\DriverException)

How could i fix that?

**Comment by sVeloper** [comment]
I could fix this problem.
behat-configuration should looks like that:

```
firefox34W7:
  extensions:
    Behat\Symfony2Extension: ~
    Behat\MinkExtension:
      base_url: http://localhost.com/myItems
      browser_name: firefox
      default_session: selenium2
      selenium2:
        wd_host: http://hub.selenium.intern.com:4444/wd/hub
        capabilities: {'platform':'WINDOWS', 'browser':'firefox', 'version':'34'}
  suites:
    mink_session:
      contexts:
        - FeatureContext:
```
