### ISSUE TITLE
default contexts

### ISSUE THREAD

**Issue by mathroc** [Behat/Behat#925]
We are in currently using traits to group step definitions but we'd like to move to using different classes but it means we have a longer behat.yaml and as we have a few context, each one needs to list every contexts it need to uses AFAICT. somethign like that:

```yaml
default:
    suites:
        suite1:
            paths:    [ %paths.base%/features ]
            contexts:
                - Common\ContextA
                - Common\ContextB
                - Common\ContextC
                - Common\ContextD
                - Common\ContextE
                - Suite1\ContextA
                - Suite1\ContextB
            filters:
                tags: "~@suite1"
        suite2:
            paths:    [ %paths.base%/features ]
            contexts:
                - Common\ContextA
                - Common\ContextB
                - Common\ContextC
                - Common\ContextD
                - Common\ContextE
                - Suite2\ContextA
            filters:
                tags: "~@suite2"
        suite3:
            paths:    [ %paths.base%/features ]
            contexts:
                - Common\ContextA
                - Common\ContextB
                - Common\ContextC
                - Common\ContextD
                - Common\ContextE
                - Suite3\ContextA
                - Suite3\ContextB
                - Suite3\ContextC
            filters:
                tags: "~@suite3"
```

we'll probably have even more contexts shared between all suites of a profile

would it be possible to define default profiles contexts ? I'm thinking about something like that:

```yaml
default:
    suites:
        suite1:
            paths:    [ %paths.base%/features ]
            contexts:
                - Suite1\ContextA
                - Suite1\ContextB
            filters:
                tags: "~@suite1"
        suite2:
            paths:    [ %paths.base%/features ]
            contexts:
                - Suite2\ContextA
            filters:
                tags: "~@suite2"
        suite3:
            paths:    [ %paths.base%/features ]
            contexts:
                - Suite3\ContextA
                - Suite3\ContextB
                - Suite3\ContextC
            filters:
                tags: "~@suite3"
    contexts:
        - Common\ContextA
        - Common\ContextB
        - Common\ContextC
        - Common\ContextD
        - Common\ContextE
```

it would make it much easier to read and update the behat.yml file

another option would be to provide default for more than contexts, eg:

```yaml
default:
    suites:
        suite1:
            contexts:
                - Suite1\ContextA
                - Suite1\ContextB
            filters:
                tags: "~@suite1"
        suite2:
            contexts:
                - Suite2\ContextA
            filters:
                tags: "~@suite2"
        suite3:
            contexts:
                - Suite3\ContextA
                - Suite3\ContextB
                - Suite3\ContextC
            filters:
                tags: "~@suite3"
    default:
        paths:    [ %paths.base%/features ]
        contexts:
            - Common\ContextA
            - Common\ContextB
            - Common\ContextC
            - Common\ContextD
            - Common\ContextE
```

what do you think ?

I can take a look at making a PR if this something that could be useful for the project

**Comment by spolischook** [comment]
We have the same needs, and implement ```common_contexts``` in own extension.
See
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/TestFrameworkBundle/Resources/config/behat.yml.dist#L21
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/TestFrameworkBundle/Behat/ServiceContainer/OroTestFrameworkExtension.php#L181

**Comment by mathroc** [comment]
thank you @spolischook for your links, turns out I forgot about yaml anchors. after some tinkering, here is what I came up with:

```yaml
default:
    suites:
        defaults:
            enabled: false
            paths: &paths
                - '%paths.base%/features'
            contexts: &contexts
                ca: Common\ContextA
                cb: Common\ContextB
                cc: Common\ContextC
                cd: Common\ContextD
                ce: Common\ContextE
        suite1:
            paths: *paths
            contexts:
                sa: Suite1\ContextA
                sb: Suite1\ContextB
            filters:
                tags: "~@suite1"
        suite2:
            paths: *paths
            contexts:
                sa: Suite2\ContextA
            filters:
                tags: "~@suite2"
        suite3:
            paths: *paths
            contexts:
                sa: Suite3\ContextA
                sb: Suite3\ContextB
                sc: Suite3\ContextC
            filters:
                tags: "~@suite3"
```

it's a bit of a hack but it works! (note that `contexts` can also be an object) 
it might be more flexible than my earlier suggestions. only pain point I can see is that anchors have to be defined before they can be used. so I can't put all that stuff at the bottom of the file (don't know if it's a yaml restriction or a restriction of the symfony yaml parser)

**Comment by everzet** [comment]
This is not the hack, this yaml feature is the reason why we never planned any complicated configuration merge capabilities.

**Comment by mathroc** [comment]
well, I said a hack because I need to have a suite with `enabled: false` (I don't where else I could put that) and as the yaml merge feature is not that advanced it's not very user friendly. I had to use objects instead of the previous array and if I want to have a default for the whole suite I have to override `enabled : true` and I can't have a "deep merge" :

```yaml
default_suite: &default_suite
  contexts:
    - c1
    - c2
my_suite:
  <<: *default_suite
  contexts: # this will be [c3] not [c1, c2, c3]
    - c3
```

but that's enough :) just not really easy to use it
