### ISSUE TITLE
Unexpected scenarios are running with tag filtering in suites/profiles

### ISSUE THREAD

**Issue by bizmate** [Behat/Behat#957]
As per topic https://groups.google.com/forum/#!topic/behat/Z0n7oR3xZtM

Assuming I have config

```yml
default:
  extensions:
    SensioLabs\Behat\PageObjectExtension: ~
    Laracasts\Behat:
      env_path: .env.behat
    Behat\MinkExtension:
      default_session: laravel
      sessions:
        default:
          laravel: ~
      base_url: 'http://localhost'
      laravel: ~
      files_path: /v3/features/assets
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: index
      print_args: true
      print_outp: true
      loop_break: true
  formatters:
    pretty:
      verbose: true
      paths: false
      snippets: true
    html:
      output_path: /tmp/behatReport

laravel:
  suites:
    laravel:
      contexts:
        - FeatureContext
        - LanguageContext
      filters:
          tags: "@int"
    html:
      output_path: /tmp/behatReportLaravel
```
And using packages

```
vagrant@vagrant-ubuntu-trusty-64:/project/v3$ composer info | grep behat
behat/behat                            v3.1.0                Scenario-oriented BDD framework for PHP 5.3
behat/debug-extension                  1.0                   Debug Behat scenarios and print any information to command line
behat/gherkin                          v4.4.1                Gherkin DSL parser for PHP 5.3
behat/mink                             v1.7.1                Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver           v1.3.2                Symfony2 BrowserKit driver for Mink framework
behat/mink-extension                   v2.2                  Mink extension for Behat
behat/mink-goutte-driver               v1.2.1                Goutte driver for Mink framework
behat/mink-selenium2-driver            v1.3.1                Selenium2 (WebDriver) driver for Mink framework
behat/transliterator                   v1.1.0                String transliterator
emuse/behat-html-formatter             v0.1.0                This will create a html formatter for Behat.
laracasts/behat-laravel-extension      1.0                   Laravel extension for Behat
sensiolabs/behat-page-object-extension v2.0.0                Page object extension for Behat
```

When running behat with profile laravel i expect that only features with int are running. Instead other features are running as well for instance:

`root@0951f5c878a3:/v3# vendor/bin/behat --profile=laravel`

```
@auth
Feature: Authentication
....
```

Also the steps in the LanguageContext are not included
``` 
FeatureContext has missing steps. Define them with these snippets:

    /**
     * @Given my language is :arg1
     */
    public function myLanguageIs($arg1)
    {
        throw new PendingException();
    }
```
Anyone has any idea of what is happening? This used to work and code specific to this
