### ISSUE TITLE
Is it possible to use environment variables inside behat.yml?

### ISSUE THREAD

**Issue by bwowk** [Behat/Behat#982]
Is there any way to make[ environment variables](https://symfony.com/doc/current/configuration/external_parameters.html#environment-variables) like %env(VAR_NAME)% work on behat.yml?
i.e.:
```
default:
    extensions: 
        Behat\MinkExtension:
            browser_stack:
                username: '%env(BROWSERSTACK_USER)%'
                access_key: '%env(BROWSERSTACK_KEY)%'
```
